begin;
select plan(36);
select has_table('public', 'applications');
select has_table('public', 'audit_logs');
select has_table('public', 'notifications');
select col_is_pk('public', 'user_roles', array['user_id','role']);
select policies_are('public', 'applications', array['applications_first_decision','applications_public_insert','applications_staff_read']);
select policies_are('public', 'notifications', array['notifications_own_read','notifications_own_update']);
select has_function('public', 'decide_application', array['uuid','application_status','text']);
select results_eq($$select model from public.agents where id='ceo'$$, $$values('gemini-2.5-flash'::text)$$, 'agent model mirrors its provider');
select results_eq($$select public.has_role('owner')$$, $$values(false)$$, 'anonymous caller has no owner role');
select results_eq($$select public.is_admin()$$, $$values(false)$$, 'anonymous caller is not admin');
select has_table('public', 'departments');
select has_table('public', 'onboarding_items');
select has_table('public', 'calendar_events');
select has_table('public', 'announcements');
select has_table('public', 'employee_documents');
select has_table('public', 'employee_kpis');
select has_table('public', 'performance_reviews');
select has_column('public', 'profiles', 'department_id');
select has_column('public', 'profiles', 'employment_status');
select results_eq($$select public.has_role('employee')$$, $$values(false)$$, 'anonymous caller has no employee role');
select results_eq($$select public.is_account_active()$$, $$values(false)$$, 'anonymous caller is not an active employee');
select results_eq($$select public from storage.buckets where id='employee-documents'$$, $$values(false)$$, 'employee documents bucket is private');
select has_table('public', 'project_milestones');
select has_table('public', 'project_meetings');
select has_table('public', 'project_kpis');
select has_table('public', 'project_files');
select has_table('public', 'project_file_permissions');
select has_table('public', 'project_activity');
select has_table('public', 'llm_providers');
select has_column('public', 'agent_runs', 'classification');
select has_column('public', 'agent_runs', 'approval_state');
select has_function('public', 'provider_accepts', array['text','data_class']);
select has_function('public', 'approve_agent_run', array['uuid','approval_status','text']);
select results_eq($$select public.provider_accepts('gemini','restricted')$$, $$values(false)$$, 'external provider is refused restricted data');
select results_eq($$select public.provider_accepts('gemini','internal')$$, $$values(true)$$, 'external provider may handle internal data');
select results_eq($$select enabled from public.agents where id='hr'$$, $$values(false)$$, 'HR agent stays disabled while only an external provider is enabled');
select * from finish();
rollback;
