import React from 'react';
import { ArrowUpRight, Banknote, BriefcaseBusiness, CheckCircle2, CircleDollarSign, FileCheck2, FolderKanban, Handshake, Plus, RefreshCw, RotateCcw, X } from 'lucide-react';
import { firstError, list, messageFor, run, type AppError } from './db';
import type { Page } from './routes';
import { useSession } from './shell';
import { supabase } from './supabase';

type Lang='ar'|'en';
type Stage='opportunity'|'quoted'|'contracted'|'delivery'|'invoiced'|'collected'|'closed'|'cancelled';
type Case={id:string;title:string;company_id:string|null;deal_id:string|null;stage:Stage;value:number;currency:string;quote_id:string|null;contract_id:string|null;project_id:string|null;invoice_id:string|null;updated_at:string};
type Deal={id:string;title:string;company_id:string|null;stage:string;value:number;currency:string};
type Company={id:string;name:string};
type Document={id:string;number:number;kind:string;amount:number;currency:string;paid_amount:number;status:string;due_date:string|null;business_case_id:string|null};
type Payment={id:string;business_case_id:string;amount:number;currency:string;paid_on:string;method:string;reference:string|null;status:string;created_at:string};
type Event={id:number;business_case_id:string;event_type:string;from_stage:string|null;to_stage:string|null;note:string;created_at:string};
const tr=(lang:Lang,ar:string,en:string)=>lang==='ar'?ar:en;
export const flowStages:Stage[]=['opportunity','quoted','contracted','delivery','invoiced','collected'];
export const nextBusinessStage=(stage:Stage):Stage|null=>({opportunity:'quoted',quoted:'contracted',contracted:'delivery',delivery:'invoiced',invoiced:null,collected:'closed',closed:null,cancelled:null}[stage] as Stage|null);
const stageText:Record<Stage,{ar:string;en:string}>={opportunity:{ar:'فرصة',en:'Opportunity'},quoted:{ar:'عرض سعر',en:'Quoted'},contracted:{ar:'متعاقد',en:'Contracted'},delivery:{ar:'قيد التنفيذ',en:'Delivery'},invoiced:{ar:'بانتظار التحصيل',en:'Collection'},collected:{ar:'تم التحصيل',en:'Collected'},closed:{ar:'مغلق',en:'Closed'},cancelled:{ar:'ملغي',en:'Cancelled'}};
const nextAction:Partial<Record<Stage,{ar:string;en:string}>>={opportunity:{ar:'إصدار عرض السعر',en:'Issue quote'},quoted:{ar:'اعتماد العقد',en:'Approve contract'},contracted:{ar:'بدء المشروع',en:'Start project'},delivery:{ar:'إصدار الفاتورة',en:'Issue invoice'},collected:{ar:'إغلاق العمل',en:'Close engagement'}};

export function BusinessFlow({lang,go}:{lang:Lang;go:(page:Page)=>void}){
  const {roles}=useSession();
  const [cases,setCases]=React.useState<Case[]>([]),[deals,setDeals]=React.useState<Deal[]>([]),[companies,setCompanies]=React.useState<Company[]>([]),[documents,setDocuments]=React.useState<Document[]>([]),[payments,setPayments]=React.useState<Payment[]>([]),[events,setEvents]=React.useState<Event[]>([]);
  const [error,setError]=React.useState<AppError|null>(null),[busy,setBusy]=React.useState(true),[message,setMessage]=React.useState('');
  const [creating,setCreating]=React.useState(false),[transition,setTransition]=React.useState<{row:Case;stage:Stage}|null>(null),[paying,setPaying]=React.useState<Case|null>(null),[reversing,setReversing]=React.useState<Payment|null>(null);
  const isFinance=roles.some(role=>['owner','super_admin'].includes(role));
  const isManager=roles.some(role=>['owner','super_admin','admin'].includes(role));
  const load=React.useCallback(async()=>{
    if(!supabase)return;setBusy(true);
    const results=await Promise.all([
      list<Case>(supabase.from('business_cases').select('*').order('updated_at',{ascending:false})),
      list<Deal>(supabase.from('crm_deals').select('id,title,company_id,stage,value,currency').neq('stage','lost').order('updated_at',{ascending:false})),
      list<Company>(supabase.from('crm_companies').select('id,name').order('name')),
      list<Document>(supabase.from('finance_documents').select('id,number,kind,amount,currency,paid_amount,status,due_date,business_case_id').order('created_at',{ascending:false})),
      list<Payment>(supabase.from('finance_payments').select('id,business_case_id,amount,currency,paid_on,method,reference,status,created_at').order('created_at',{ascending:false})),
      list<Event>(supabase.from('business_case_events').select('id,business_case_id,event_type,from_stage,to_stage,note,created_at').order('created_at',{ascending:false}).limit(500)),
    ]);
    setError(firstError(results));
    if(results[0].ok)setCases(results[0].data);if(results[1].ok)setDeals(results[1].data);if(results[2].ok)setCompanies(results[2].data);if(results[3].ok)setDocuments(results[3].data);if(results[4].ok)setPayments(results[4].data);if(results[5].ok)setEvents(results[5].data);
    setBusy(false);
  },[]);
  React.useEffect(()=>{void load();},[load]);
  const perform=async<T,>(promise:PromiseLike<{data:T|null;error:unknown}>,success:string)=>{setBusy(true);setMessage('');const result=await run<T>(promise);if(!result.ok)setError(result.error);else{setError(null);setMessage(success);await load();}setBusy(false);return result.ok;};
  const create=async(event:React.FormEvent<HTMLFormElement>)=>{event.preventDefault();if(!supabase)return;const data=new FormData(event.currentTarget);const ok=await perform(supabase.rpc('create_business_case_from_deal',{wanted_deal:String(data.get('deal'))}),tr(lang,'تم فتح دورة العمل.','Business flow opened.'));if(ok)setCreating(false);};
  const advance=async(event:React.FormEvent<HTMLFormElement>)=>{event.preventDefault();if(!supabase||!transition)return;const data=new FormData(event.currentTarget),reason=String(data.get('reason'));const action=transition.stage==='cancelled'?supabase.rpc('cancel_business_case',{wanted_case:transition.row.id,change_reason:reason}):supabase.rpc('advance_business_case',{wanted_case:transition.row.id,requested_stage:transition.stage,change_reason:reason});const ok=await perform(action,transition.stage==='cancelled'?tr(lang,'تم إلغاء العمل وتوثيق السبب.','Engagement cancelled and reason recorded.'):tr(lang,'تم تنفيذ المرحلة وتوثيقها.','Stage completed and recorded.'));if(ok)setTransition(null);};
  const recordPayment=async(event:React.FormEvent<HTMLFormElement>)=>{event.preventDefault();if(!supabase||!paying)return;const data=new FormData(event.currentTarget);const ok=await perform(supabase.rpc('record_business_payment',{wanted_case:paying.id,payment_amount:Number(data.get('amount')),payment_method:String(data.get('method')),payment_reference:String(data.get('reference')||'')||null,payment_date:String(data.get('paid_on')),payment_notes:String(data.get('notes')||'')}),tr(lang,'تم تسجيل الدفعة وتحديث الرصيد.','Payment recorded and balance updated.'));if(ok)setPaying(null);};
  const reversePayment=async(event:React.FormEvent<HTMLFormElement>)=>{event.preventDefault();if(!supabase||!reversing)return;const data=new FormData(event.currentTarget);const ok=await perform(supabase.rpc('reverse_business_payment',{wanted_payment:reversing.id,reason:String(data.get('reason'))}),tr(lang,'تم عكس الدفعة وإعادة فتح الرصيد.','Payment reversed and balance reopened.'));if(ok)setReversing(null);};
  const companyName=(id:string|null)=>companies.find(row=>row.id===id)?.name||tr(lang,'عميل غير محدد','Unassigned customer');
  const money=(value:number,currency='OMR')=>new Intl.NumberFormat(lang==='ar'?'ar-OM':'en-OM',{style:'currency',currency}).format(Number(value)||0);
  const caseDocument=(row:Case,kind:'quote'|'invoice')=>documents.find(doc=>doc.id===(kind==='quote'?row.quote_id:row.invoice_id));
  const openDeals=deals.filter(deal=>!cases.some(row=>row.deal_id===deal.id));
  const openCases=cases.filter(row=>!['closed','cancelled'].includes(row.stage));
  const pipeline=openCases.reduce((sum,row)=>sum+Number(row.value),0);
  const receivable=documents.filter(row=>row.kind==='invoice'&&!['void','paid'].includes(row.status)).reduce((sum,row)=>sum+Number(row.amount)-Number(row.paid_amount),0);
  const allowedNext=(row:Case)=>{const next=nextBusinessStage(row.stage);if(!next)return null;if(['contracted','delivery','closed'].includes(next)&&!isManager)return null;if(next==='invoiced'&&!isFinance)return null;return next;};
  return <main className="os-page os-business"><div className="os-page-heading"><div><span className="os-eyebrow">REID / BUSINESS FLOW</span><h1>{tr(lang,'من أول فرصة إلى آخر ريال.','From first opportunity to final collection.')}</h1><p>{tr(lang,'مسار واحد يربط المبيعات والعقود والمشاريع والفواتير بدون سجلات متفرقة.','One accountable flow connecting sales, contracts, projects, invoices, and cash.')}</p></div><div className="os-heading-actions"><button className="os-secondary" onClick={()=>void load()} disabled={busy}><RefreshCw/>{tr(lang,'تحديث','Refresh')}</button><button className="os-primary" onClick={()=>setCreating(true)} disabled={!openDeals.length}><Plus/>{tr(lang,'ابدأ من صفقة','Start from a deal')}</button></div></div>
    {error&&<p className="os-alert" role="alert">{messageFor(error,lang)}</p>}{message&&<p className="os-success" role="status">{message}</p>}
    <div className="os-metrics"><section><span><BriefcaseBusiness/><small>{tr(lang,'أعمال نشطة','Active engagements')}</small></span><b>{busy?'—':openCases.length}</b></section><section><span><CircleDollarSign/><small>{tr(lang,'قيمة المسار','Flow value')}</small></span><b>{busy?'—':money(pipeline)}</b></section><section><span><FolderKanban/><small>{tr(lang,'قيد التنفيذ','In delivery')}</small></span><b>{busy?'—':cases.filter(row=>row.stage==='delivery').length}</b></section><section><span><Banknote/><small>{tr(lang,'رصيد مستحق','Outstanding')}</small></span><b>{busy?'—':money(receivable)}</b></section></div>
    <section className="os-flow-board">{flowStages.map(stage=><div className="os-flow-column" key={stage}><header><span>{lang==='ar'?stageText[stage].ar:stageText[stage].en}</span><b>{cases.filter(row=>row.stage===stage).length}</b></header>{cases.filter(row=>row.stage===stage).map(row=>{const invoice=caseDocument(row,'invoice'),paid=invoice?.paid_amount||0,balance=(invoice?.amount||row.value)-paid,next=allowedNext(row),canCancel=isManager&&(!['invoiced','collected'].includes(row.stage)||isFinance);return <article className="os-flow-card" key={row.id}><small>{companyName(row.company_id)}</small><h2>{row.title}</h2><strong>{money(row.value,row.currency)}</strong>{row.stage==='invoiced'&&invoice&&<div className="os-payment-progress"><span style={{width:`${Math.min(100,(paid/Number(invoice.amount||1))*100)}%`}}/><small>{tr(lang,`المتبقي ${money(balance,row.currency)}`,`${money(balance,row.currency)} remaining`)}</small></div>}<div className="os-flow-links">{row.quote_id&&<button onClick={()=>go('finance')}><FileCheck2/>{tr(lang,'العرض','Quote')}</button>}{row.project_id&&<button onClick={()=>{go('projects');history.replaceState({},'',`/projects/${row.project_id}`);dispatchEvent(new PopStateEvent('popstate'));}}><FolderKanban/>{tr(lang,'المشروع','Project')}</button>}{row.invoice_id&&<button onClick={()=>go('finance')}><Banknote/>{tr(lang,'الفاتورة','Invoice')}</button>}</div><div className="os-flow-actions">{next&&<button className="os-primary" onClick={()=>setTransition({row,stage:next})}>{tr(lang,nextAction[row.stage]?.ar||stageText[next].ar,nextAction[row.stage]?.en||stageText[next].en)}<ArrowUpRight/></button>}{row.stage==='invoiced'&&isFinance&&<button className="os-primary" onClick={()=>setPaying(row)}>{tr(lang,'سجّل دفعة','Record payment')}</button>}{canCancel&&<button className="os-secondary" onClick={()=>setTransition({row,stage:'cancelled'})}><X/>{tr(lang,'إلغاء العمل','Cancel')}</button>}</div><details><summary>{tr(lang,'السجل والدفعات','History & payments')}</summary><div className="os-flow-history">{payments.filter(p=>p.business_case_id===row.id).map(payment=><p key={payment.id}><span><b>{money(payment.amount,payment.currency)}</b><small>{payment.paid_on} · {payment.method}</small></span><i className={`os-status ${payment.status==='posted'?'good':''}`}>{payment.status}</i>{payment.status==='posted'&&isFinance&&<button onClick={()=>setReversing(payment)}><RotateCcw/>{tr(lang,'عكس','Reverse')}</button>}</p>)}{events.filter(item=>item.business_case_id===row.id).slice(0,8).map(item=><p key={item.id}><span><b>{lang==='ar'?(item.to_stage?stageText[item.to_stage as Stage]?.ar:item.event_type):(item.to_stage?stageText[item.to_stage as Stage]?.en:item.event_type)}</b><small>{item.note} · {new Date(item.created_at).toLocaleDateString(lang==='ar'?'ar-OM':'en-OM')}</small></span></p>)}</div></details></article>})}<div className="os-flow-empty">{tr(lang,'لا توجد أعمال','No engagements')}</div></div>)}</section>
    {!!cases.some(row=>['closed','cancelled'].includes(row.stage))&&<section className="os-panel os-flow-archive"><h2>{tr(lang,'الأعمال المغلقة','Closed engagements')}</h2>{cases.filter(row=>['closed','cancelled'].includes(row.stage)).map(row=><span key={row.id}><b>{row.title}</b><small>{companyName(row.company_id)}</small><i className="os-status">{lang==='ar'?stageText[row.stage].ar:stageText[row.stage].en}</i></span>)}</section>}
    {creating&&<Modal lang={lang} title={tr(lang,'ابدأ دورة عمل من صفقة','Start a business flow from a deal')} close={()=>setCreating(false)}><form onSubmit={e=>void create(e)}><label>{tr(lang,'الصفقة','Deal')}<select name="deal" required defaultValue=""><option value="" disabled>{tr(lang,'اختر صفقة','Choose a deal')}</option>{openDeals.map(deal=><option key={deal.id} value={deal.id}>{deal.title} · {companyName(deal.company_id)} · {money(deal.value,deal.currency)}</option>)}</select></label><button className="os-primary" disabled={busy}>{tr(lang,'فتح دورة العمل','Open business flow')}</button></form></Modal>}
    {transition&&<Modal lang={lang} title={transition.stage==='cancelled'?tr(lang,'إلغاء العمل','Cancel engagement'):tr(lang,nextAction[transition.row.stage]?.ar||stageText[transition.stage].ar,nextAction[transition.row.stage]?.en||stageText[transition.stage].en)} close={()=>setTransition(null)}><form onSubmit={e=>void advance(e)}><p>{transition.row.title}</p><label>{transition.stage==='cancelled'?tr(lang,'سبب الإلغاء','Cancellation reason'):tr(lang,'سبب القرار أو ملاحظته','Decision reason or note')}<textarea name="reason" required maxLength={500} autoFocus/></label><button className="os-primary" disabled={busy}>{transition.stage==='cancelled'?tr(lang,'تأكيد الإلغاء','Confirm cancellation'):tr(lang,'تأكيد وتنفيذ','Confirm and execute')}</button></form></Modal>}
    {paying&&<Modal lang={lang} title={tr(lang,'تسجيل دفعة','Record payment')} close={()=>setPaying(null)}><form onSubmit={e=>void recordPayment(e)}><p>{paying.title}</p><div className="os-form-row"><label>{tr(lang,'المبلغ','Amount')}<input name="amount" type="number" min="0.001" step="0.001" max={caseDocument(paying,'invoice')?Number(caseDocument(paying,'invoice')!.amount)-Number(caseDocument(paying,'invoice')!.paid_amount):undefined} required autoFocus/></label><label>{tr(lang,'التاريخ','Date')}<input name="paid_on" type="date" defaultValue={new Date().toISOString().slice(0,10)} required/></label></div><label>{tr(lang,'طريقة الدفع','Payment method')}<select name="method"><option value="bank_transfer">{tr(lang,'تحويل بنكي','Bank transfer')}</option><option value="cash">{tr(lang,'نقد','Cash')}</option><option value="card">{tr(lang,'بطاقة','Card')}</option><option value="cheque">{tr(lang,'شيك','Cheque')}</option><option value="other">{tr(lang,'أخرى','Other')}</option></select></label><label>{tr(lang,'المرجع','Reference')}<input name="reference" maxLength={120}/></label><label>{tr(lang,'ملاحظة','Note')}<textarea name="notes" maxLength={500}/></label><button className="os-primary" disabled={busy}>{tr(lang,'تسجيل الدفعة','Record payment')}</button></form></Modal>}
    {reversing&&<Modal lang={lang} title={tr(lang,'عكس الدفعة','Reverse payment')} close={()=>setReversing(null)}><form onSubmit={e=>void reversePayment(e)}><p>{money(reversing.amount,reversing.currency)} · {reversing.paid_on}</p><label>{tr(lang,'سبب العكس','Reversal reason')}<textarea name="reason" required maxLength={500} autoFocus/></label><button className="os-primary" disabled={busy}>{tr(lang,'تأكيد العكس','Confirm reversal')}</button></form></Modal>}
  </main>;
}

function Modal({lang,title,close,children}:{lang:Lang;title:string;close:()=>void;children:React.ReactNode}){return <div className="os-modal-backdrop"><section className="os-modal" role="dialog" aria-modal="true" aria-label={title}><div className="os-section-title"><h2>{title}</h2><button onClick={close} aria-label={tr(lang,'إغلاق','Close')}><X/></button></div>{children}</section></div>;}
