import React from 'react';
import { ArrowUpRight, AtSign, Bot, CheckCircle2, Clock3, FolderKanban, Plus, Search, X, Sparkles, Send, FileText, CalendarDays, Circle, RefreshCw, BriefcaseBusiness, UsersRound, ShieldCheck } from 'lucide-react';
import { supabase } from './supabase';
import { list, run, messageFor, toAppError } from './db';
import { useSession } from './shell';
import { agentRunResult, loadAgentControl, runAgent } from './agents';
import type { AgentRow } from './agents';
import { agentNames, ensureAgentRoom, loadAgentRoomMessages, postAgentRoomMessage, resolveAgentHandoffs, resolveAgentMentions, roomHistory, teamRequest } from './agent-room';
import type { AgentRoom, AgentRoomMessage } from './agent-room';
import type { Page } from './routes';

type Lang='ar'|'en';
const tr=(lang:Lang,ar:string,en:string)=>lang==='ar'?ar:en;
type Task={id:string;title:string;status:string;priority:number;due_at:string|null;project_id:string|null};
type Project={id:string;name:string;status:string;type:string};
type Notice={id:string;title_ar:string;title_en:string;read_at:string|null;created_at:string};

export function Today({lang,go}:{lang:Lang;go:(page:Page)=>void}) {
  const {user,roles}=useSession();
  const [tasks,setTasks]=React.useState<Task[]>([]),[projects,setProjects]=React.useState<Project[]>([]),[notices,setNotices]=React.useState<Notice[]>([]);
  const [busy,setBusy]=React.useState(true),[error,setError]=React.useState(''),[title,setTitle]=React.useState(''),[saving,setSaving]=React.useState(false);
  const load=React.useCallback(async()=>{
    if(!supabase||!user)return;setBusy(true);
    const results=await Promise.all([
      list<Task>(supabase.from('tasks').select('id,title,status,priority,due_at,project_id').eq('assignee_id',user.id).neq('status','done').order('due_at',{nullsFirst:false}).limit(30)),
      list<Project>(supabase.from('projects').select('id,name,status,type').order('created_at',{ascending:false}).limit(6)),
      list<Notice>(supabase.from('notifications').select('id,title_ar,title_en,read_at,created_at').order('created_at',{ascending:false}).limit(8)),
    ]);
    const failure=results.find(x=>!x.ok);setError(failure&&!failure.ok?messageFor(failure.error,lang):'');
    if(results[0].ok)setTasks(results[0].data);if(results[1].ok)setProjects(results[1].data);if(results[2].ok)setNotices(results[2].data);setBusy(false);
  },[user,lang]);
  React.useEffect(()=>{void load();},[load]);
  const complete=async(task:Task)=>{if(!supabase)return;const result=await run(supabase.from('tasks').update({status:'done'}).eq('id',task.id).select('id').single());if(!result.ok)setError(messageFor(result.error,lang));else await load();};
  const add=async(e:React.FormEvent)=>{e.preventDefault();if(!supabase||!user||!title.trim())return;setSaving(true);const result=await run(supabase.from('tasks').insert({title:title.trim(),assignee_id:user.id,created_by:user.id}).select('id').single());if(!result.ok)setError(messageFor(result.error,lang));else{setTitle('');await load();}setSaving(false);};
  const canCreate=roles.some(x=>['owner','super_admin','admin','hr'].includes(x));const canUseAssistant=roles.some(x=>['owner','super_admin','admin'].includes(x));
  const name=user?.user_metadata?.full_name?.split(' ')[0]||tr(lang,'بك','there');
  return <main className="os-page"><div className="os-page-heading"><div><span className="os-eyebrow">{new Intl.DateTimeFormat(lang==='ar'?'ar-OM':'en-GB',{weekday:'long',day:'numeric',month:'long',timeZone:'Asia/Muscat'}).format(new Date())}</span><h1>{tr(lang,`أهلًا ${name}، خلّنا ننجز.`,`Hello ${name}. Let's make progress.`)}</h1><p>{tr(lang,'صورة واضحة ليومك. وخطوة تالية لكل عمل.','A clear view of your day. A next step for every piece of work.')}</p></div><button className="os-secondary" onClick={()=>void load()} disabled={busy}><RefreshCw/>{tr(lang,'تحديث','Refresh')}</button></div>
    {error&&<p className="os-alert" role="alert">{error}</p>}
    <div className="os-metrics">{[[tr(lang,'مهامي المفتوحة','My open tasks'),tasks.length,<CheckCircle2/>],[tr(lang,'تحتاج متابعة اليوم','Due or overdue'),tasks.filter(t=>t.due_at&&Date.parse(t.due_at)<Date.now()).length,<Clock3/>],[tr(lang,'مشاريع حديثة ظاهرة لي','Recent visible projects'),projects.length,<FolderKanban/>],[tr(lang,'تنبيهات غير مقروءة ظاهرة','Visible unread updates'),notices.filter(x=>!x.read_at).length,<CalendarDays/>]].map(([label,value,icon],i)=><section key={i}><span>{icon}<small>{label}</small></span><b>{busy?'—':value}</b></section>)}</div>
    <div className="os-day-grid"><section className="os-panel"><div className="os-section-title"><h2>{tr(lang,'التركيز اليوم','Your focus')}</h2><span className="os-status">{tasks.length} {tr(lang,'مهمة','tasks')}</span></div>
      {canCreate&&<form className="os-quick-add" onSubmit={e=>void add(e)}><Plus/><input aria-label={tr(lang,'مهمة جديدة','New task')} placeholder={tr(lang,'ما الخطوة التالية؟ أضف مهمة…','What is next? Add a task…')} value={title} maxLength={200} onChange={e=>setTitle(e.target.value)}/><button disabled={saving||!title.trim()}>{tr(lang,'إضافة','Add')}</button></form>}
      {tasks.map(task=><div className="os-task" key={task.id}><button aria-label={tr(lang,'إكمال المهمة','Complete task')} onClick={()=>void complete(task)}><Circle/></button><div><b>{task.title}</b><small>{projects.find(p=>p.id===task.project_id)?.name||tr(lang,'مساحتي','My workspace')}</small></div>{task.due_at&&<time className={Date.parse(task.due_at)<Date.now()?'overdue':''}>{new Date(task.due_at).toLocaleDateString(lang==='ar'?'ar-OM':'en-GB',{day:'numeric',month:'short'})}</time>}</div>)}
      {!busy&&!tasks.length&&<div className="os-empty"><CheckCircle2/><h3>{tr(lang,'مساحة ليوم منتج','Room for a productive day')}</h3><p>{tr(lang,'ما عندك مهام مفتوحة مسندة لك حاليًا.','You have no open tasks assigned to you right now.')}</p></div>}
    </section><div className="os-stack"><section className="os-panel os-assistant-intro"><Sparkles/><span className="os-eyebrow">REID AGENT TEAM</span><h2>{tr(lang,'ابدأ يومك مع الفريق.','Start the day with your team.')}</h2><p>{tr(lang,'كلّف وكيلًا أو اجمع عدة مختصين لمراجعة العمل وتحديد الخطوة التالية.','Assign one agent or bring specialists together to review work and choose the next step.')}</p><button className="os-primary" onClick={()=>go(canUseAssistant?'assistant':'workspace')}>{tr(lang,canUseAssistant?'افتح فريق الوكلاء':'افتح مساحة الفريق',canUseAssistant?'Open agent team':'Open people workspace')}<ArrowUpRight/></button></section>
      <section className="os-panel"><div className="os-section-title"><h2>{tr(lang,'آخر المستجدات','Latest updates')}</h2></div>{notices.map(n=><div className="os-update" key={n.id}><span className={n.read_at?'':'unread'}/><div><p>{lang==='ar'?n.title_ar:n.title_en}</p><small>{new Date(n.created_at).toLocaleDateString(lang==='ar'?'ar-OM':'en-GB')}</small></div></div>)}{!notices.length&&<p className="os-muted">{tr(lang,'لا توجد مستجدات ظاهرة لك.','No updates are visible to you.')}</p>}</section></div></div>
    <div className="os-section-title os-spaced"><h2>{tr(lang,'مساحات يتحرك فيها العمل','Where work moves forward')}</h2><button onClick={()=>go('projects')}>{tr(lang,'كل المشاريع','All projects')}<ArrowUpRight/></button></div><div className="os-projects">{projects.map(p=><button key={p.id} className="os-panel os-project-card" onClick={()=>{go('projects');history.replaceState({},'',`/projects/${p.id}`);dispatchEvent(new PopStateEvent('popstate'));}}><FolderKanban/><span className="os-status">{p.status}</span><h3>{p.name}</h3><p>{p.type}</p><span>{tr(lang,'افتح مساحة المشروع','Open project workspace')}<ArrowUpRight/></span></button>)}</div>
  </main>;
}

type WorkRecord={id:string;kind:string;title:string;description:string;status:string;due_date:string|null;owner_id:string};
const kinds=[['goal','الأهداف','Goals'],['ticket','الدعم','Support'],['leave','الإجازات','Leave'],['asset','العهد والأصول','Assets'],['content','المحتوى','Content'],['decision','القرارات','Decisions'],['contract','العقود','Contracts']];
export function Operations({lang}:{lang:Lang}) {
  const {roles,user}=useSession();const privileged=roles.some(x=>['owner','super_admin'].includes(x));
  const allowed=kinds.filter(([k])=>privileged||['ticket','leave'].includes(k)||(roles.includes('admin')&&['goal','asset','content','decision'].includes(k)));
  const [kind,setKind]=React.useState(allowed[0]?.[0]||'ticket'),[rows,setRows]=React.useState<WorkRecord[]>([]),[query,setQuery]=React.useState(''),[error,setError]=React.useState(''),[adding,setAdding]=React.useState(false),[saving,setSaving]=React.useState(false),[busy,setBusy]=React.useState(true);
  const load=React.useCallback(async()=>{if(!supabase)return;setBusy(true);const result=await list<WorkRecord>(supabase.from('work_records').select('*').eq('kind',kind).order('created_at',{ascending:false}).limit(200));if(result.ok){setRows(result.data);setError('');}else setError(messageFor(result.error,lang));setBusy(false);},[kind,lang]);
  React.useEffect(()=>{void load();},[load]);
  const create=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();if(!supabase)return;setSaving(true);const data=new FormData(e.currentTarget);const result=await run(supabase.from('work_records').insert({kind,title:String(data.get('title')).trim(),description:String(data.get('description')||''),due_date:data.get('due')||null,owner_id:user?.id}).select('id').single());if(result.ok){setAdding(false);await load();}else setError(messageFor(result.error,lang));setSaving(false);};
  const change=async(row:WorkRecord,status:string)=>{if(!supabase)return;const result=await run(supabase.from('work_records').update({status}).eq('id',row.id).select('id').single());if(!result.ok)setError(messageFor(result.error,lang));else await load();};
  const statusNames:Record<string,string>={open:tr(lang,'مفتوح','Open'),in_progress:tr(lang,'قيد العمل','In progress'),review:tr(lang,'للمراجعة','Review'),done:tr(lang,'مكتمل','Done'),cancelled:tr(lang,'ملغي','Cancelled')};
  return <main className="os-page"><div className="os-page-heading"><div><span className="os-eyebrow">REID / OPERATIONS</span><h1>{tr(lang,'التفاصيل التي تحرّك الشركة.','The details that move a company.')}</h1><p>{tr(lang,'أهداف وطلبات وقرارات؛ بمسؤولية واضحة وسجل محفوظ.','Goals, requests and decisions with clear ownership and a durable record.')}</p></div><button className="os-primary" onClick={()=>setAdding(true)}><Plus/>{tr(lang,'سجل جديد','New record')}</button></div>
    <div className="os-tabs">{allowed.map(([key,ar,en])=><button aria-pressed={kind===key} key={key} onClick={()=>{setRows([]);setKind(key);}}>{tr(lang,ar,en)}</button>)}</div>
    {error&&<p className="os-alert" role="alert">{error}</p>}
    <section className="os-panel"><label className="os-search"><Search/><input placeholder={tr(lang,'ابحث في السجلات…','Search records…')} aria-label={tr(lang,'بحث السجلات','Search records')} value={query} onChange={e=>setQuery(e.target.value)}/></label>
      {rows.filter(r=>r.title.includes(query)).map(row=><div className="os-record" key={row.id}><span className="os-icon"><FileText/></span><div><b>{row.title}</b><p>{row.description}</p>{row.due_date&&<small>{row.due_date}</small>}</div><select aria-label={tr(lang,'حالة السجل','Record status')} value={row.status} onChange={e=>void change(row,e.target.value)}>{Object.entries(statusNames).filter(([key])=>kind!=='leave'||privileged||roles.includes('hr')||['open','cancelled'].includes(key)||key===row.status).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></div>)}
      {!rows.length&&<div className="os-empty"><BriefcaseBusiness/><h3>{busy?tr(lang,'جارٍ التحميل…','Loading…'):tr(lang,'ابدأ بأول سجل','Start with your first record')}</h3><p>{tr(lang,'كل سجل يوضح المطلوب وحالته وتاريخ استحقاقه.','Each record captures the work, its status and due date.')}</p></div>}
    </section>
    {adding&&<div className="os-modal-backdrop"><section className="os-modal" role="dialog" aria-modal="true" aria-labelledby="record-title"><div className="os-section-title"><h2 id="record-title">{tr(lang,'سجل جديد','New record')}</h2><button onClick={()=>setAdding(false)} aria-label={tr(lang,'إغلاق','Close')}><X/></button></div><form onSubmit={e=>void create(e)}><label>{tr(lang,'العنوان','Title')}<input name="title" required maxLength={250} autoFocus/></label><label>{tr(lang,'التفاصيل','Details')}<textarea name="description" rows={4}/></label><label>{tr(lang,'تاريخ الاستحقاق','Due date')}<input type="date" name="due"/></label><button className="os-primary" disabled={saving}>{tr(lang,'حفظ السجل','Save record')}</button></form></section></div>}
  </main>;
}

export function AssistantWorkspace({lang}:{lang:Lang}) {
  const {user}=useSession();
  const [room,setRoom]=React.useState<AgentRoom|null>(null),[agents,setAgents]=React.useState<AgentRow[]>([]),[messages,setMessages]=React.useState<AgentRoomMessage[]>([]);
  const [input,setInput]=React.useState(''),[busy,setBusy]=React.useState(false),[loading,setLoading]=React.useState(true),[error,setError]=React.useState('');
  const [messageQuery,setMessageQuery]=React.useState(''),[agentFilter,setAgentFilter]=React.useState('all');
  const bottom=React.useRef<HTMLDivElement>(null);
  const refreshMessages=React.useCallback(async(currentRoom=room)=>{if(!currentRoom)return;setMessages(await loadAgentRoomMessages(currentRoom.id));},[room]);

  React.useEffect(()=>{if(!user)return;let alive=true;(async()=>{setLoading(true);try{const [currentRoom,control]=await Promise.all([ensureAgentRoom(user.id,lang),loadAgentControl()]);if(!alive)return;setRoom(currentRoom);setAgents(control.agents.filter(agent=>agent.id in agentNames));setMessages(await loadAgentRoomMessages(currentRoom.id));setError('');}catch(cause){if(alive)setError(messageFor(toAppError(cause),lang));}finally{if(alive)setLoading(false);}})();return()=>{alive=false;};},[user,lang]);
  React.useEffect(()=>{if(!room||!supabase)return;const client=supabase;const channel=client.channel(`agent-team-room-${room.id}`).on('postgres_changes',{event:'*',schema:'public',table:'agent_room_messages',filter:`room_id=eq.${room.id}`},payload=>{const row=(payload.new||payload.old) as AgentRoomMessage;setMessages(current=>payload.eventType==='DELETE'?current.filter(message=>message.id!==row.id):[...current.filter(message=>message.id!==row.id),row].sort((a,b)=>a.created_at.localeCompare(b.created_at)));}).subscribe();return()=>{void client.removeChannel(channel);};},[room]);
  React.useEffect(()=>{bottom.current?.scrollIntoView({behavior:'smooth',block:'end'});},[messages]);

  const waitForResult=async(runId:string)=>{for(let attempt=0;attempt<72;attempt+=1){const result=await agentRunResult(runId);if(['succeeded','failed','cancelled'].includes(result.status))return result;await new Promise(resolve=>window.setTimeout(resolve,2500));}throw new Error('agent_team_timeout');};
  const mention=(id:string)=>setInput(value=>`${value}${value&&!/\s$/.test(value)?' ':''}@${id} `);
  const mentionMatch=input.match(/(?:^|\s)@([\p{L}\p{N}_-]*)$/u),mentionTerm=mentionMatch?.[1]?.toLocaleLowerCase()||'';
  const mentionCandidates=mentionMatch?agents.filter(agent=>agent.enabled&&(agent.id.includes(mentionTerm)||(agentNames[agent.id]?.[lang]||agent.name).toLocaleLowerCase().includes(mentionTerm))).slice(0,6):[];
  const chooseMention=(id:string)=>setInput(value=>value.replace(/@([\p{L}\p{N}_-]*)$/u,`@${id} `));
  const targets=resolveAgentMentions(input,agents,false);
  const visibleMessages=messages.filter(message=>(agentFilter==='all'||message.sender_agent_id===agentFilter||(agentFilter==='owner'&&message.sender_kind==='user'))&&(!messageQuery.trim()||message.body.toLocaleLowerCase().includes(messageQuery.trim().toLocaleLowerCase())));
  const stateText=(message:AgentRoomMessage)=>message.state==='pending_approval'?tr(lang,'ينتظر موافقتك','Waiting for approval'):message.state==='queued'?tr(lang,'في طابور التنفيذ…','Queued…'):message.state==='running'?tr(lang,'يعمل على المهمة…','Working…'):message.state==='failed'?tr(lang,'تعذر تنفيذ المهمة.','The task failed.'):message.state==='cancelled'?tr(lang,'أُلغيت المهمة.','Task cancelled.'):message.body;
  const send=async(e:React.FormEvent)=>{e.preventDefault();if(!room||!user||!input.trim()||busy)return;const text=input.trim(),targets=resolveAgentMentions(text,agents);setInput('');setBusy(true);setError('');try{const userMessage=await postAgentRoomMessage(room.id,user.id,text,targets);setMessages(current=>[...current.filter(message=>message.id!==userMessage.id),userMessage]);const queue=targets.map(id=>({id,replyTo:userMessage.id})),processed=new Set<string>();let automaticHandoffs=0;const failures:string[]=[];while(queue.length){const item=queue.shift()!;if(processed.has(item.id))continue;processed.add(item.id);try{const current=await loadAgentRoomMessages(room.id),result=await runAgent(item.id,teamRequest(item.id,text,lang),'internal',roomHistory(current,lang),{roomId:room.id,replyToMessageId:item.replyTo});let output=result.output||'';if(['queued','running'].includes(result.status||'')){const completed=await waitForResult(result.runId);if(completed.status!=='succeeded')throw new Error(`agent_run_${completed.status}`);output=completed.output||'';}const updated=await loadAgentRoomMessages(room.id);setMessages(updated);const agentMessage=updated.find(message=>message.run_id===result.runId);for(const handoff of resolveAgentHandoffs(output,agents)){if(!processed.has(handoff)&&!queue.some(next=>next.id===handoff)&&automaticHandoffs<3){queue.push({id:handoff,replyTo:agentMessage?.id||userMessage.id});automaticHandoffs+=1;}}}catch(cause){failures.push(`${agentNames[item.id]?.[lang]||item.id}: ${messageFor(toAppError(cause),lang)}`);}}if(failures.length)setError(failures.join('\n'));await refreshMessages(room);}catch(cause){setError(messageFor(toAppError(cause),lang));}finally{setBusy(false);}};

  return <main className="os-page os-agent-team"><div className="os-page-heading"><div><span className="os-eyebrow">REID / AGENT TEAM ROOM</span><h1>{tr(lang,'فريقك الذكي، في غرفة عمل واحدة.','Your AI team, in one working room.')}</h1><p>{tr(lang,'كلّف مختصًا، اجمع أكثر من وكيل، وتابع تسليم العمل بينهم.','Assign a specialist, bring agents together, and follow every handoff.')}</p></div><span className="os-agent-room-status"><UsersRound/>{agents.filter(agent=>agent.enabled).length} {tr(lang,'جاهزون للعمل','ready to work')}</span></div>
    <div className="os-agent-team-shell"><section className="os-panel os-agent-team-room">
      <header className="os-agent-team-header"><div><span className="os-agent-team-avatar"><UsersRound/></span><div><b>{room?.name||tr(lang,'فريق ريّد','Reid agent team')}</b><small>{tr(lang,'غرفة خاصة بك · محفوظة ومباشرة','Private to you · saved and live')}</small></div></div><div className="os-agent-team-toolbar"><label><Search/><input value={messageQuery} onChange={event=>setMessageQuery(event.target.value)} placeholder={tr(lang,'ابحث في المحادثة…','Search this room…')}/></label><select value={agentFilter} onChange={event=>setAgentFilter(event.target.value)} aria-label={tr(lang,'تصفية حسب المرسل','Filter by sender')}><option value="all">{tr(lang,'كل الرسائل','All messages')}</option><option value="owner">{tr(lang,'رسائلي','My messages')}</option>{agents.map(agent=><option key={agent.id} value={agent.id}>{agentNames[agent.id]?.[lang]||agent.name}</option>)}</select></div></header>
      {!messages.length&&!loading&&<div className="os-assistant-welcome os-agent-team-welcome"><span className="os-icon"><UsersRound/></span><h2>{tr(lang,'ابدأ اجتماع الفريق.','Start the team meeting.')}</h2><p>{tr(lang,'اختر وكيلًا أو اكتب مباشرة؛ المدير المنسّق يستلم الرسائل التي بلا منشن.','Choose an agent or just write; the orchestrator receives messages without a mention.')}</p><div className="os-suggestions">{[tr(lang,'@operations راجع حالة المشاريع وحدد العوائق','@operations review project status and identify blockers'),tr(lang,'@marketing و @content جهزوا خطة محتوى للأسبوع','@marketing and @content prepare this week’s content plan'),tr(lang,'@ceo وزّع أولويات اليوم على الفريق','@ceo assign today’s priorities to the team')].map(suggestion=><button type="button" onClick={()=>setInput(suggestion)} key={suggestion}>{suggestion}<ArrowUpRight/></button>)}</div></div>}
      <div className="os-message-list os-agent-team-messages" aria-live="polite">{visibleMessages.map(message=>{const mine=message.sender_kind==='user',name=mine?tr(lang,'أنت','You'):(agentNames[message.sender_agent_id||'']?.[lang]||message.sender_agent_id||tr(lang,'النظام','System')),parent=message.reply_to?messages.find(candidate=>candidate.id===message.reply_to):null;return <article className={`os-message ${mine?'outbound':'inbound'} agent-team-message`} data-state={message.state} key={message.id}><span className="agent-message-avatar">{mine?<AtSign/>:<Bot/>}</span><div><header><b>{name}</b>{message.sender_agent_id&&<small>@{message.sender_agent_id}</small>}<time>{new Date(message.created_at).toLocaleTimeString(lang==='ar'?'ar-OM':'en-GB',{hour:'2-digit',minute:'2-digit'})}</time></header>{parent&&<small className="agent-message-reply">↳ {parent.sender_kind==='user'?tr(lang,'رد على المالك','Reply to Owner'):`@${parent.sender_agent_id}`}</small>}<p>{stateText(message)}</p>{message.state!=='completed'&&message.state!=='failed'&&message.state!=='cancelled'&&<small className="agent-message-progress"><Clock3/>{stateText(message)}</small>}</div></article>;})}{messages.length&&!visibleMessages.length&&<div className="os-empty"><Search/><h3>{tr(lang,'لا توجد رسائل مطابقة','No matching messages')}</h3><p>{tr(lang,'غيّر البحث أو اختر كل الرسائل.','Change the search or show all messages.')}</p></div>}<div ref={bottom}/></div>
      {loading&&<p className="os-agent-team-loading"><RefreshCw/>{tr(lang,'جارٍ فتح غرفة الفريق…','Opening the team room…')}</p>}{error&&<p role="alert" className="os-alert">{error}</p>}
      <form className="os-composer os-agent-team-composer" onSubmit={e=>void send(e)}><div className="os-composer-context"><button type="button" onClick={()=>setInput(value=>`${value}${value&&!/\s$/.test(value)?' ':''}@`)}><AtSign/>{tr(lang,'اذكر وكيلًا','Mention agent')}</button>{targets.map(id=><span key={id}>@{id}</span>)}{!targets.length&&<small>{tr(lang,'بدون منشن: يستلمها المدير المنسّق','No mention: routed to the orchestrator')}</small>}</div><div className="os-agent-input-wrap">{mentionCandidates.length>0&&<div className="os-mention-menu">{mentionCandidates.map(agent=><button type="button" key={agent.id} onClick={()=>chooseMention(agent.id)}><span><Bot/></span><div><b>{agentNames[agent.id]?.[lang]||agent.name}</b><small>@{agent.id}</small></div></button>)}</div>}<textarea maxLength={8000} aria-label={tr(lang,'رسالتك لفريق الوكلاء','Message the agent team')} placeholder={tr(lang,'اكتب المهمة، واستخدم @ لاختيار المختص…','Describe the work and use @ to choose a specialist…')} value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey&&!mentionCandidates.length){e.preventDefault();e.currentTarget.form?.requestSubmit();}}}/><button className="os-primary" disabled={busy||loading||!input.trim()}>{busy?<RefreshCw className="spin"/>:<Send/>}{busy?tr(lang,'الفريق يعمل…','Team working…'):tr(lang,'إرسال','Send')}</button></div></form><small className="os-muted os-agent-team-note">{tr(lang,'Enter للإرسال وShift + Enter لسطر جديد. أي إجراء حساس يبقى في مسار الموافقة.','Enter sends; Shift + Enter adds a line. Sensitive actions stay in the approval flow.')}</small>
    </section><aside className="os-panel os-agent-team-side"><div className="os-section-title"><div><span className="os-eyebrow">TEAM</span><h2>{tr(lang,'المختصون','Specialists')}</h2></div><span className="os-status good">{agents.filter(agent=>agent.enabled&&agent.status!=='paused').length}</span></div><div className="os-agent-directory">{agents.map(agent=><button type="button" key={agent.id} data-state={!agent.enabled?'blocked':agent.status==='paused'?'paused':'ready'} onClick={()=>mention(agent.id)}><span><Bot/></span><div><b>{agentNames[agent.id]?.[lang]||agent.name}</b><small>@{agent.id}</small></div><i>{!agent.enabled?tr(lang,'متوقف','Blocked'):agent.status==='paused'?tr(lang,'موقوف مؤقتًا','Paused'):tr(lang,'جاهز','Ready')}</i></button>)}</div><div className="os-agent-room-summary"><div><span>{tr(lang,'الرسائل','Messages')}</span><b>{messages.length}</b></div><div><span>{tr(lang,'قيد العمل','In progress')}</span><b>{messages.filter(message=>['queued','running','pending_approval'].includes(message.state)).length}</b></div><div><span>{tr(lang,'تحتاج مراجعة','Need review')}</span><b>{messages.filter(message=>message.state==='failed'||message.state==='pending_approval').length}</b></div></div><p><ShieldCheck/>{tr(lang,'ردود الوكلاء موثقة بتشغيل حقيقي. الإجراءات الحساسة لا تنفّذ دون موافقتك.','Agent replies are tied to real runs. Sensitive actions wait for your approval.')}</p></aside></div></main>;
}
