import React from 'react';
import { ArrowUpRight, CheckCircle2, Clock3, FolderKanban, Plus, Search, X, Sparkles, Send, FileText, CalendarDays, Circle, RefreshCw, Wallet, UsersRound, Target, BriefcaseBusiness } from 'lucide-react';
import { supabase } from './supabase';
import { list, run, messageFor, toAppError } from './db';
import { useSession } from './shell';
import { runAgent } from './agents';
import type { Page } from './routes';

type Lang='ar'|'en';
const tr=(lang:Lang,ar:string,en:string)=>lang==='ar'?ar:en;
type Task={id:string;title:string;status:string;priority:number;due_at:string|null;project_id:string|null};
type Project={id:string;name:string;status:string;type:string};
type Notice={id:string;title_ar:string;title_en:string;read_at:string|null;created_at:string};

export function Today({lang,go}:{lang:Lang;go:(page:Page)=>void}) {
  const {user,roles}=useSession();
  const [tasks,setTasks]=React.useState<Task[]>([]),[projects,setProjects]=React.useState<Project[]>([]),[notices,setNotices]=React.useState<Notice[]>([]);
  const [busy,setBusy]=React.useState(true),[error,setError]=React.useState(''),[title,setTitle]=React.useState(''),[saving,setSaving]=React.useState(false);
  const load=React.useCallback(async()=>{
    if(!supabase||!user)return;setBusy(true);
    const results=await Promise.all([
      list<Task>(supabase.from('tasks').select('id,title,status,priority,due_at,project_id').eq('assignee_id',user.id).neq('status','done').order('due_at',{nullsFirst:false}).limit(30)),
      list<Project>(supabase.from('projects').select('id,name,status,type').order('created_at',{ascending:false}).limit(6)),
      list<Notice>(supabase.from('notifications').select('id,title_ar,title_en,read_at,created_at').order('created_at',{ascending:false}).limit(8)),
    ]);
    const failure=results.find(x=>!x.ok);setError(failure&&!failure.ok?messageFor(failure.error,lang):'');
    if(results[0].ok)setTasks(results[0].data);if(results[1].ok)setProjects(results[1].data);if(results[2].ok)setNotices(results[2].data);setBusy(false);
  },[user,lang]);
  React.useEffect(()=>{void load();},[load]);
  const complete=async(task:Task)=>{if(!supabase)return;const result=await run(supabase.from('tasks').update({status:'done'}).eq('id',task.id).select('id').single());if(!result.ok)setError(messageFor(result.error,lang));else await load();};
  const add=async(e:React.FormEvent)=>{e.preventDefault();if(!supabase||!user||!title.trim())return;setSaving(true);const result=await run(supabase.from('tasks').insert({title:title.trim(),assignee_id:user.id,created_by:user.id}).select('id').single());if(!result.ok)setError(messageFor(result.error,lang));else{setTitle('');await load();}setSaving(false);};
  const canCreate=roles.some(x=>['owner','super_admin','admin','hr'].includes(x));const canUseAssistant=roles.some(x=>['owner','super_admin','admin'].includes(x));
  const name=user?.user_metadata?.full_name?.split(' ')[0]||tr(lang,'بك','there');
  return <main className="os-page"><div className="os-page-heading"><div><span className="os-eyebrow">{new Intl.DateTimeFormat(lang==='ar'?'ar-OM':'en-GB',{weekday:'long',day:'numeric',month:'long',timeZone:'Asia/Muscat'}).format(new Date())}</span><h1>{tr(lang,`أهلًا ${name}، خلّنا ننجز.`,`Hello ${name}. Let's make progress.`)}</h1><p>{tr(lang,'صورة واضحة ليومك. وخطوة تالية لكل عمل.','A clear view of your day. A next step for every piece of work.')}</p></div><button className="os-secondary" onClick={()=>void load()} disabled={busy}><RefreshCw/>{tr(lang,'تحديث','Refresh')}</button></div>
    {error&&<p className="os-alert" role="alert">{error}</p>}
    <div className="os-metrics">{[[tr(lang,'مهامي المفتوحة','My open tasks'),tasks.length,<CheckCircle2/>],[tr(lang,'تحتاج متابعة اليوم','Due or overdue'),tasks.filter(t=>t.due_at&&Date.parse(t.due_at)<Date.now()).length,<Clock3/>],[tr(lang,'مشاريع حديثة ظاهرة لي','Recent visible projects'),projects.length,<FolderKanban/>],[tr(lang,'تنبيهات غير مقروءة ظاهرة','Visible unread updates'),notices.filter(x=>!x.read_at).length,<CalendarDays/>]].map(([label,value,icon],i)=><section key={i}><span>{icon}<small>{label}</small></span><b>{busy?'—':value}</b></section>)}</div>
    <div className="os-day-grid"><section className="os-panel"><div className="os-section-title"><h2>{tr(lang,'التركيز اليوم','Your focus')}</h2><span className="os-status">{tasks.length} {tr(lang,'مهمة','tasks')}</span></div>
      {canCreate&&<form className="os-quick-add" onSubmit={e=>void add(e)}><Plus/><input aria-label={tr(lang,'مهمة جديدة','New task')} placeholder={tr(lang,'ما الخطوة التالية؟ أضف مهمة…','What is next? Add a task…')} value={title} maxLength={200} onChange={e=>setTitle(e.target.value)}/><button disabled={saving||!title.trim()}>{tr(lang,'إضافة','Add')}</button></form>}
      {tasks.map(task=><div className="os-task" key={task.id}><button aria-label={tr(lang,'إكمال المهمة','Complete task')} onClick={()=>void complete(task)}><Circle/></button><div><b>{task.title}</b><small>{projects.find(p=>p.id===task.project_id)?.name||tr(lang,'مساحتي','My workspace')}</small></div>{task.due_at&&<time className={Date.parse(task.due_at)<Date.now()?'overdue':''}>{new Date(task.due_at).toLocaleDateString(lang==='ar'?'ar-OM':'en-GB',{day:'numeric',month:'short'})}</time>}</div>)}
      {!busy&&!tasks.length&&<div className="os-empty"><CheckCircle2/><h3>{tr(lang,'مساحة ليوم منتج','Room for a productive day')}</h3><p>{tr(lang,'ما عندك مهام مفتوحة مسندة لك حاليًا.','You have no open tasks assigned to you right now.')}</p></div>}
    </section><div className="os-stack"><section className="os-panel os-assistant-intro"><Sparkles/><span className="os-eyebrow">REID INTELLIGENCE</span><h2>{tr(lang,'فكّر بصوت عالٍ.','Think out loud.')}</h2><p>{tr(lang,'رتّب أفكارك، افهم سير المشاريع، وجهّز خطوتك التالية مع مساعد ريّد.','Organize ideas, understand delivery, and prepare your next step with Reid.')}</p><button className="os-secondary" onClick={()=>go(canUseAssistant?'assistant':'workspace')}>{tr(lang,canUseAssistant?'افتح المساعد':'افتح مساحة العمل',canUseAssistant?'Open assistant':'Open workspace')}<ArrowUpRight/></button></section>
      <section className="os-panel"><div className="os-section-title"><h2>{tr(lang,'آخر المستجدات','Latest updates')}</h2></div>{notices.map(n=><div className="os-update" key={n.id}><span className={n.read_at?'':'unread'}/><div><p>{lang==='ar'?n.title_ar:n.title_en}</p><small>{new Date(n.created_at).toLocaleDateString(lang==='ar'?'ar-OM':'en-GB')}</small></div></div>)}{!notices.length&&<p className="os-muted">{tr(lang,'لا توجد مستجدات ظاهرة لك.','No updates are visible to you.')}</p>}</section></div></div>
    <div className="os-section-title os-spaced"><h2>{tr(lang,'مساحات يتحرك فيها العمل','Where work moves forward')}</h2><button onClick={()=>go('projects')}>{tr(lang,'كل المشاريع','All projects')}<ArrowUpRight/></button></div><div className="os-projects">{projects.map(p=><button key={p.id} className="os-panel os-project-card" onClick={()=>{go('projects');history.replaceState({},'',`/projects/${p.id}`);dispatchEvent(new PopStateEvent('popstate'));}}><FolderKanban/><span className="os-status">{p.status}</span><h3>{p.name}</h3><p>{p.type}</p><span>{tr(lang,'افتح مساحة المشروع','Open project workspace')}<ArrowUpRight/></span></button>)}</div>
  </main>;
}

type WorkRecord={id:string;kind:string;title:string;description:string;status:string;due_date:string|null;owner_id:string};
const kinds=[['goal','الأهداف','Goals'],['ticket','الدعم','Support'],['leave','الإجازات','Leave'],['purchase','المشتريات','Purchases'],['asset','العهد والأصول','Assets'],['content','المحتوى','Content'],['decision','القرارات','Decisions'],['contract','العقود','Contracts']];
export function Operations({lang}:{lang:Lang}) {
  const {roles,user}=useSession();const privileged=roles.some(x=>['owner','super_admin'].includes(x));
  const allowed=kinds.filter(([k])=>privileged||['ticket','leave'].includes(k)||(roles.includes('admin')&&['goal','asset','content','decision'].includes(k)));
  const [kind,setKind]=React.useState(allowed[0]?.[0]||'ticket'),[rows,setRows]=React.useState<WorkRecord[]>([]),[query,setQuery]=React.useState(''),[error,setError]=React.useState(''),[adding,setAdding]=React.useState(false),[saving,setSaving]=React.useState(false),[busy,setBusy]=React.useState(true);
  const load=React.useCallback(async()=>{if(!supabase)return;setBusy(true);const result=await list<WorkRecord>(supabase.from('work_records').select('*').eq('kind',kind).order('created_at',{ascending:false}).limit(200));if(result.ok){setRows(result.data);setError('');}else setError(messageFor(result.error,lang));setBusy(false);},[kind,lang]);
  React.useEffect(()=>{void load();},[load]);
  const create=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();if(!supabase)return;setSaving(true);const data=new FormData(e.currentTarget);const result=await run(supabase.from('work_records').insert({kind,title:String(data.get('title')).trim(),description:String(data.get('description')||''),due_date:data.get('due')||null,owner_id:user?.id}).select('id').single());if(result.ok){setAdding(false);await load();}else setError(messageFor(result.error,lang));setSaving(false);};
  const change=async(row:WorkRecord,status:string)=>{if(!supabase)return;const result=await run(supabase.from('work_records').update({status}).eq('id',row.id).select('id').single());if(!result.ok)setError(messageFor(result.error,lang));else await load();};
  const statusNames:Record<string,string>={open:tr(lang,'مفتوح','Open'),in_progress:tr(lang,'قيد العمل','In progress'),review:tr(lang,'للمراجعة','Review'),done:tr(lang,'مكتمل','Done'),cancelled:tr(lang,'ملغي','Cancelled')};
  return <main className="os-page"><div className="os-page-heading"><div><span className="os-eyebrow">REID / OPERATIONS</span><h1>{tr(lang,'التفاصيل التي تحرّك الشركة.','The details that move a company.')}</h1><p>{tr(lang,'أهداف وطلبات وقرارات؛ بمسؤولية واضحة وسجل محفوظ.','Goals, requests and decisions with clear ownership and a durable record.')}</p></div><button className="os-primary" onClick={()=>setAdding(true)}><Plus/>{tr(lang,'سجل جديد','New record')}</button></div>
    <div className="os-tabs">{allowed.map(([key,ar,en])=><button aria-pressed={kind===key} key={key} onClick={()=>{setRows([]);setKind(key);}}>{tr(lang,ar,en)}</button>)}</div>
    {error&&<p className="os-alert" role="alert">{error}</p>}
    <section className="os-panel"><label className="os-search"><Search/><input placeholder={tr(lang,'ابحث في السجلات…','Search records…')} aria-label={tr(lang,'بحث السجلات','Search records')} value={query} onChange={e=>setQuery(e.target.value)}/></label>
      {rows.filter(r=>r.title.includes(query)).map(row=><div className="os-record" key={row.id}><span className="os-icon"><FileText/></span><div><b>{row.title}</b><p>{row.description}</p>{row.due_date&&<small>{row.due_date}</small>}</div><select aria-label={tr(lang,'حالة السجل','Record status')} value={row.status} onChange={e=>void change(row,e.target.value)}>{Object.entries(statusNames).filter(([key])=>kind!=='leave'||privileged||roles.includes('hr')||['open','cancelled'].includes(key)||key===row.status).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></div>)}
      {!rows.length&&<div className="os-empty"><BriefcaseBusiness/><h3>{busy?tr(lang,'جارٍ التحميل…','Loading…'):tr(lang,'ابدأ بأول سجل','Start with your first record')}</h3><p>{tr(lang,'كل سجل يوضح المطلوب وحالته وتاريخ استحقاقه.','Each record captures the work, its status and due date.')}</p></div>}
    </section>
    {adding&&<div className="os-modal-backdrop"><section className="os-modal" role="dialog" aria-modal="true" aria-labelledby="record-title"><div className="os-section-title"><h2 id="record-title">{tr(lang,'سجل جديد','New record')}</h2><button onClick={()=>setAdding(false)} aria-label={tr(lang,'إغلاق','Close')}><X/></button></div><form onSubmit={e=>void create(e)}><label>{tr(lang,'العنوان','Title')}<input name="title" required maxLength={250} autoFocus/></label><label>{tr(lang,'التفاصيل','Details')}<textarea name="description" rows={4}/></label><label>{tr(lang,'تاريخ الاستحقاق','Due date')}<input type="date" name="due"/></label><button className="os-primary" disabled={saving}>{tr(lang,'حفظ السجل','Save record')}</button></form></section></div>}
  </main>;
}

type FinanceRow={id:string;number:number;kind:string;title:string;counterparty:string;amount:number;currency:string;status:string;due_date:string|null;notes:string};
export function Finance({lang}:{lang:Lang}) {
  const [kind,setKind]=React.useState('invoice'),[rows,setRows]=React.useState<FinanceRow[]>([]),[error,setError]=React.useState(''),[adding,setAdding]=React.useState(false),[saving,setSaving]=React.useState(false),[busy,setBusy]=React.useState(true);
  const load=React.useCallback(async()=>{if(!supabase)return;setBusy(true);const result=await list<FinanceRow>(supabase.from('finance_documents').select('*').order('created_at',{ascending:false}).limit(200));if(result.ok){setRows(result.data);setError('');}else setError(messageFor(result.error,lang));setBusy(false);},[lang]);React.useEffect(()=>{void load();},[load]);
  const create=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();if(!supabase)return;setSaving(true);const f=new FormData(e.currentTarget);const result=await run(supabase.from('finance_documents').insert({kind,title:f.get('title'),counterparty:f.get('counterparty'),amount:Number(f.get('amount')),currency:f.get('currency'),due_date:f.get('due')||null,notes:f.get('notes')||''}).select('id').single());if(result.ok){setAdding(false);await load();}else setError(messageFor(result.error,lang));setSaving(false);};
  const change=async(row:FinanceRow,status:string)=>{if(!supabase)return;if(!window.confirm(tr(lang,`تأكيد تغيير حالة «${row.title}»؟ تسجيل الدفع هنا يوثق دفعة تمت خارج النظام.`,`Confirm status change for “${row.title}”? Recording payment documents a payment made outside this system.`)))return;const result=await run(supabase.from('finance_documents').update({status}).eq('id',row.id).select('id').single());if(!result.ok)setError(messageFor(result.error,lang));else await load();};
  const names:Record<string,string>={draft:tr(lang,'مسودة','Draft'),issued:tr(lang,'صادر','Issued'),approved:tr(lang,'معتمد','Approved'),paid:tr(lang,'مدفوع','Paid'),void:tr(lang,'ملغي','Void')};
  const cash=(value:number,currency='OMR')=>new Intl.NumberFormat(lang==='ar'?'ar-OM':'en-OM',{style:'currency',currency}).format(value);
  const local=rows.filter(x=>x.currency==='OMR');
  return <main className="os-page"><div className="os-page-heading"><div><span className="os-eyebrow">REID / FINANCE</span><h1>{tr(lang,'وضوح في كل مبلغ.','Clarity in every amount.')}</h1><p>{tr(lang,'عروض وفواتير ومصروفات، وسجل واضح للتحصيل.','Quotes, invoices, expenses, and a clear collection record.')}</p></div><button className="os-primary" onClick={()=>setAdding(true)}><Plus/>{tr(lang,'مستند جديد','New document')}</button></div>
    {error&&<p className="os-alert" role="alert">{error}</p>}
    <div className="os-metrics">{[[tr(lang,'فواتير مستحقة · OMR','Receivable · OMR'),local.filter(x=>x.kind==='invoice'&&['issued','approved'].includes(x.status)).reduce((s,x)=>s+Number(x.amount),0)],[tr(lang,'تحصيل مسجل · OMR','Recorded receipts · OMR'),local.filter(x=>x.kind==='invoice'&&x.status==='paid').reduce((s,x)=>s+Number(x.amount),0)],[tr(lang,'مصروفات مدفوعة · OMR','Paid expenses · OMR'),local.filter(x=>x.kind==='expense'&&x.status==='paid').reduce((s,x)=>s+Number(x.amount),0)]].map(([label,value],i)=><section key={i}><span><Wallet/><small>{label}</small></span><b>{busy?'—':cash(Number(value))}</b></section>)}</div><p className="os-muted">{tr(lang,'الملخص لآخر 200 مستند وبالريال العُماني فقط. التسجيل لا ينفّذ تحويلًا ماليًا.','Summary covers the latest 200 documents in OMR only. Recording does not execute a financial transfer.')}</p>
    <div className="os-tabs">{[['invoice','الفواتير','Invoices'],['quote','عروض الأسعار','Quotes'],['expense','المصروفات','Expenses']].map(([key,ar,en])=><button key={key} aria-pressed={kind===key} onClick={()=>setKind(key)}>{tr(lang,ar,en)}</button>)}</div><section className="os-panel">
    {rows.filter(x=>x.kind===kind).map(row=><div className="os-record" key={row.id}><span className="os-icon"><FileText/></span><div><small>REID-{String(row.number).padStart(5,'0')}</small><b>{row.title}</b><p>{row.counterparty} {row.due_date?`· ${row.due_date}`:''}</p></div><strong>{cash(Number(row.amount),row.currency)}</strong><select aria-label={tr(lang,'حالة المستند','Document status')} value={row.status} disabled={['paid','void'].includes(row.status)} onChange={e=>void change(row,e.target.value)}>{[row.status,...(row.status==='draft'?['issued','void']:row.status==='issued'?['approved',...(row.kind==='quote'?[]:['paid']),'void']:row.status==='approved'?[...(row.kind==='quote'?[]:['paid']),'void']:[])].map(key=><option key={key} value={key}>{names[key]}</option>)}</select></div>)}
    {!rows.some(x=>x.kind===kind)&&<div className="os-empty"><FileText/><h3>{busy?tr(lang,'جارٍ التحميل…','Loading…'):tr(lang,'مستنداتك تبدأ هنا','Your documents start here')}</h3><p>{tr(lang,'أضف المستند، ثم تابعه حتى الاعتماد أو التحصيل.','Add a document, then track approval or collection.')}</p></div>}</section>
    {adding&&<div className="os-modal-backdrop"><section className="os-modal" role="dialog" aria-modal="true" aria-labelledby="finance-title"><div className="os-section-title"><h2 id="finance-title">{tr(lang,'مستند مالي جديد','New financial document')}</h2><button aria-label={tr(lang,'إغلاق','Close')} onClick={()=>setAdding(false)}><X/></button></div><form onSubmit={e=>void create(e)}><label>{tr(lang,'العنوان','Title')}<input name="title" required maxLength={250} autoFocus/></label><label>{tr(lang,'العميل أو المورد','Customer or supplier')}<input name="counterparty" required/></label><div className="os-form-row"><label>{tr(lang,'المبلغ','Amount')}<input name="amount" type="number" min="0" step="0.001" required/></label><label>{tr(lang,'العملة','Currency')}<select name="currency">{['OMR','USD','AED','EUR'].map(c=><option key={c}>{c}</option>)}</select></label></div><label>{tr(lang,'الاستحقاق','Due date')}<input name="due" type="date"/></label><label>{tr(lang,'ملاحظات','Notes')}<textarea name="notes"/></label><button className="os-primary" disabled={saving}>{tr(lang,'حفظ كمسودة','Save draft')}</button></form></section></div>}
  </main>;
}

export function AssistantWorkspace({lang}:{lang:Lang}) {
  const [agent,setAgent]=React.useState('operations'),[input,setInput]=React.useState(''),[busy,setBusy]=React.useState(false),[error,setError]=React.useState('');
  const [messages,setMessages]=React.useState<{role:string;text:string}[]>([]);
  const [pending,setPending]=React.useState<string|null>(null);
  const send=async(e:React.FormEvent)=>{e.preventDefault();if(!input.trim()||busy)return;const text=input.trim();setInput('');setBusy(true);setError('');setMessages(v=>[...v,{role:'user',text}]);try{const result=await runAgent(agent,text,'internal');if(result.status==='queued'||result.status==='running'){setPending(result.runId);setMessages(v=>[...v,{role:'assistant',text:tr(lang,'طلبك في قائمة التنفيذ. تقدر تتابع حالته أدناه.','Your request is queued. Follow its status below.')}]);}else{setMessages(v=>[...v,{role:'assistant',text:result.output||tr(lang,'الطلب يحتاج موافقة أو متابعة من مركز الإدارة.','This request needs approval or follow-up in the command center.')}]);}}catch(e){setError(messageFor(toAppError(e),lang));}finally{setBusy(false);}};
  React.useEffect(()=>{if(!pending||!supabase)return;let alive=true;const client=supabase;const timer=setInterval(async()=>{const {data,error}=await client.functions.invoke('llm-gateway',{body:{action:'result',runId:pending}});if(!alive)return;if(error||data?.error){setError(tr(lang,'تعذر تحديث نتيجة المساعد. أعد المحاولة من مركز الإدارة.','Could not refresh the assistant result. Retry from the command center.'));return;}const row={run_state:data.status,output_preview:data.output};if(['succeeded','failed','cancelled'].includes(row.run_state)){setPending(null);setMessages(v=>[...v,{role:'assistant',text:row.run_state==='succeeded'?(row.output_preview||tr(lang,'اكتمل الطلب؛ راجع سجل التنفيذ.','Completed; see the run log.')):tr(lang,'تعذر إكمال الطلب. راجع مركز الإدارة للتفاصيل.','The request could not be completed. See the command center.')}]);}},3500);return()=>{alive=false;clearInterval(timer);};},[pending,lang]);
  return <main className="os-page"><div className="os-page-heading"><div><span className="os-eyebrow">REID / INTELLIGENCE</span><h1>{tr(lang,'فكرتك التالية تبدأ هنا.','Your next idea starts here.')}</h1><p>{tr(lang,'مساعد يعرف سياق عملك ويلتزم بصلاحياتك.','An assistant grounded in your work and your permissions.')}</p></div><select aria-label={tr(lang,'اختصاص المساعد','Assistant specialty')} value={agent} onChange={e=>setAgent(e.target.value)}>{[['operations','التشغيل','Operations'],['ceo','إدارة الشركة','Company'],['sales','المبيعات','Sales'],['knowledge','المعرفة','Knowledge'],['hr','الموظفون','People'],['finance','المالية','Finance']].map(([v,ar,en])=><option key={v} value={v}>{tr(lang,ar,en)}</option>)}</select></div><section className="os-panel os-assistant-chat">
    {!messages.length&&<div className="os-assistant-welcome"><span className="os-icon"><Sparkles/></span><h2>{tr(lang,'وش ننجز مع بعض؟','What shall we work on?')}</h2><p>{tr(lang,'ابدأ بسؤال، أو اختر نقطة انطلاق.','Ask a question, or choose a starting point.')}</p><div className="os-suggestions">{[tr(lang,'لخّص حالة المشاريع وحدد ما يحتاج متابعة','Summarize projects and identify follow-ups'),tr(lang,'ساعدني أرتب أولويات هذا الأسبوع','Help prioritize this week'),tr(lang,'اقترح خطة لمتابعة العملاء المحتملين','Suggest a lead follow-up plan')].map(text=><button onClick={()=>setInput(text)} key={text}>{text}<ArrowUpRight/></button>)}</div></div>}
    <div className="os-message-list" aria-live="polite">{messages.map((m,i)=><article className={`os-message ${m.role==='user'?'outbound':'inbound'}`} key={i}><small>{m.role==='user'?tr(lang,'أنت','You'):tr(lang,'مساعد ريّد','Reid assistant')}</small><p>{m.text}</p></article>)}</div>{pending&&<p className="os-notice"><Clock3/>{tr(lang,'بانتظار تنفيذ النموذج المحلي…','Waiting for local model execution…')}</p>}{error&&<p role="alert" className="os-alert">{error}</p>}<form className="os-composer" onSubmit={e=>void send(e)}><textarea maxLength={8000} aria-label={tr(lang,'رسالتك للمساعد','Message assistant')} placeholder={tr(lang,'اسأل عن العمل أو ابدأ بفكرة…','Ask about work, or start with an idea…')} value={input} onChange={e=>setInput(e.target.value)}/><button className="os-primary" disabled={busy||!!pending||!input.trim()}><Send/>{tr(lang,'إرسال','Send')}</button></form><small className="os-muted">{tr(lang,'الإجراءات والموافقات وسجل التنفيذ متاحة في مركز الإدارة.','Actions, approvals and execution receipts are available in the command center.')}</small>
    </section></main>;
}
