import React from 'react';
import { AlertTriangle, ArrowUpRight, Banknote, BriefcaseBusiness, CheckCircle2, CircleDollarSign, Clock3, FileCheck2, FolderKanban, RefreshCw, ShieldCheck, UsersRound } from 'lucide-react';
import { messageFor, run, type AppError } from './db';
import type { Page } from './routes';
import { supabase } from './supabase';

type Lang='ar'|'en';
const tr=(lang:Lang,ar:string,en:string)=>lang==='ar'?ar:en;
type Snapshot={
  as_of:string;currency:string;
  metrics:{active_people:number;active_projects:number;active_cases:number;pipeline_omr:number;outstanding_omr:number;collected_30d_omr:number;issued_30d_omr:number};
  alerts:{overdue_invoices:number;overdue_amount_omr:number;overdue_tasks:number;pending_approvals:number;pending_applications:number;stalled_cases:number;failed_agent_runs_7d:number};
  stages:{stage:string;count:number;value_omr:number}[];
  cash_trend:{month:string;collected_omr:number}[];
  receivables:{id:string;number:number;counterparty:string;due_date:string|null;currency:string;amount:number;paid_amount:number;balance:number;is_overdue:boolean}[];
  projects:{id:string;name:string;status:string;target_date:string|null;overdue_tasks:number;risk_count:number}[];
};

const stageText:Record<string,{ar:string;en:string}>={opportunity:{ar:'فرصة',en:'Opportunity'},quoted:{ar:'عرض سعر',en:'Quoted'},contracted:{ar:'متعاقد',en:'Contracted'},delivery:{ar:'قيد التنفيذ',en:'Delivery'},invoiced:{ar:'بانتظار التحصيل',en:'Collection'},collected:{ar:'تم التحصيل',en:'Collected'},closed:{ar:'مغلق',en:'Closed'},cancelled:{ar:'ملغي',en:'Cancelled'}};

export function OwnerOverview({lang,go}:{lang:Lang;go:(page:Page)=>void}){
  const [snapshot,setSnapshot]=React.useState<Snapshot|null>(null),[error,setError]=React.useState<AppError|null>(null),[busy,setBusy]=React.useState(true);
  const load=React.useCallback(async()=>{if(!supabase)return;setBusy(true);const result=await run<Snapshot>(supabase.rpc('owner_company_snapshot'));if(result.ok&&result.data){setSnapshot(result.data);setError(null);}else if(!result.ok)setError(result.error);setBusy(false);},[]);
  React.useEffect(()=>{void load();},[load]);
  const money=(value:number,currency='OMR')=>new Intl.NumberFormat(lang==='ar'?'ar-OM':'en-OM',{style:'currency',currency,maximumFractionDigits:3}).format(Number(value)||0);
  const month=(value:string)=>new Intl.DateTimeFormat(lang==='ar'?'ar-OM':'en-OM',{month:'short'}).format(new Date(`${value}-01T00:00:00Z`));
  const maxCash=Math.max(1,...(snapshot?.cash_trend||[]).map(item=>Number(item.collected_omr)));
  const alertRows=snapshot?[{key:'overdue',label:tr(lang,'فواتير تجاوزت الاستحقاق','Overdue invoices'),detail:money(snapshot.alerts.overdue_amount_omr),value:snapshot.alerts.overdue_invoices,go:()=>go('finance')},{key:'tasks',label:tr(lang,'مهام متأخرة','Overdue tasks'),detail:tr(lang,'تحتاج توزيع أو متابعة','Need ownership or follow-up'),value:snapshot.alerts.overdue_tasks,go:()=>go('projects')},{key:'approvals',label:tr(lang,'موافقات معلّقة','Pending approvals'),detail:tr(lang,'قرارات الوكلاء بانتظارك','Agent decisions waiting'),value:snapshot.alerts.pending_approvals,go:()=>go('admin')},{key:'applications',label:tr(lang,'طلبات انضمام','Join applications'),detail:tr(lang,'تحتاج قرارًا من الإدارة','Need a management decision'),value:snapshot.alerts.pending_applications,go:()=>go('workspace')},{key:'stalled',label:tr(lang,'أعمال بلا حركة 14 يومًا','Cases idle for 14 days'),detail:tr(lang,'راجع الخطوة التالية','Review the next step'),value:snapshot.alerts.stalled_cases,go:()=>go('business')},{key:'agents',label:tr(lang,'تشغيلات وكيل فشلت خلال 7 أيام','Agent failures in 7 days'),detail:tr(lang,'راجع السبب قبل الإعادة','Review before retrying'),value:snapshot.alerts.failed_agent_runs_7d,go:()=>go('dashboard')}]:[];
  return <main className="os-page os-owner"><div className="os-page-heading"><div><span className="os-eyebrow">REID / OWNER BRIEF</span><h1>{tr(lang,'الشركة في صورة واحدة.','The company in one view.')}</h1><p>{tr(lang,'ما دخل، وما بقي، وما يحتاج قرارك الآن.','What came in, what remains, and what needs your decision now.')}</p></div><div className="os-heading-actions"><button className="os-secondary" onClick={()=>go('admin')}><ShieldCheck/>{tr(lang,'الإدارة والصلاحيات','Admin & permissions')}</button><button className="os-primary" disabled={busy} onClick={()=>void load()}><RefreshCw/>{tr(lang,'تحديث','Refresh')}</button></div></div>
    {error&&<p className="os-alert" role="alert">{messageFor(error,lang)}</p>}
    <div className="os-owner-metrics"><Metric icon={<CircleDollarSign/>} label={tr(lang,'تحصيل آخر 30 يومًا','Collected in 30 days')} value={busy?'—':money(snapshot?.metrics.collected_30d_omr||0)} note={tr(lang,'دفعات مرحّلة بالريال العُماني','Posted OMR receipts')}/><Metric icon={<Banknote/>} label={tr(lang,'رصيد مستحق','Outstanding')} value={busy?'—':money(snapshot?.metrics.outstanding_omr||0)} note={snapshot&&snapshot.alerts.overdue_invoices?tr(lang,`${snapshot.alerts.overdue_invoices} متأخرة`,` ${snapshot.alerts.overdue_invoices} overdue`):tr(lang,'لا توجد فواتير متأخرة','No overdue invoices')} risk={!!snapshot?.alerts.overdue_invoices}/><Metric icon={<BriefcaseBusiness/>} label={tr(lang,'قيمة الأعمال النشطة','Active business value')} value={busy?'—':money(snapshot?.metrics.pipeline_omr||0)} note={tr(lang,`${snapshot?.metrics.active_cases||0} دورة عمل`,` ${snapshot?.metrics.active_cases||0} business cases`)}/><Metric icon={<FolderKanban/>} label={tr(lang,'مشاريع نشطة','Active projects')} value={busy?'—':String(snapshot?.metrics.active_projects||0)} note={tr(lang,`${snapshot?.alerts.overdue_tasks||0} مهمة متأخرة`,`${snapshot?.alerts.overdue_tasks||0} overdue tasks`)}/><Metric icon={<UsersRound/>} label={tr(lang,'حسابات شركة نشطة','Active company accounts')} value={busy?'—':String(snapshot?.metrics.active_people||0)} note={tr(lang,'دون الضيوف والحسابات المعطلة','Excludes guests and disabled accounts')}/></div>
    <div className="os-owner-grid"><section className="os-panel os-owner-cash"><div className="os-section-title"><div><h2>{tr(lang,'حركة التحصيل','Collection trend')}</h2><small>{tr(lang,'آخر 6 أشهر · OMR','Last 6 months · OMR')}</small></div><button onClick={()=>go('finance')}>{tr(lang,'المالية','Finance')}<ArrowUpRight/></button></div><div className="os-cash-chart" aria-label={tr(lang,'رسم تحصيل آخر ستة أشهر','Six-month collection chart')}>{snapshot?.cash_trend.map(item=><div key={item.month}><b>{Number(item.collected_omr)>0?money(item.collected_omr):''}</b><span><i style={{height:`${Math.max(Number(item.collected_omr)>0?8:2,Number(item.collected_omr)/maxCash*100)}%`}}/></span><small>{month(item.month)}</small></div>)}</div><div className="os-owner-issued"><span>{tr(lang,'فواتير صادرة خلال 30 يومًا','Invoices issued in 30 days')}</span><b>{money(snapshot?.metrics.issued_30d_omr||0)}</b></div></section>
      <section className="os-panel"><div className="os-section-title"><h2>{tr(lang,'يحتاج قرارك','Needs your decision')}</h2><span className={`os-status ${alertRows.some(row=>row.value)?'risk':'good'}`}>{alertRows.filter(row=>row.value).length}</span></div><div className="os-owner-alerts">{alertRows.filter(row=>row.value).map(row=><button key={row.key} onClick={row.go}><span><AlertTriangle/></span><div><b>{row.label}</b><small>{row.detail}</small></div><strong>{row.value}</strong><ArrowUpRight/></button>)}{snapshot&&!alertRows.some(row=>row.value)&&<div className="os-empty"><CheckCircle2/><h3>{tr(lang,'لا شيء حرج الآن','Nothing critical right now')}</h3><p>{tr(lang,'كل المؤشرات العاجلة ضمن السيطرة.','All urgent indicators are under control.')}</p></div>}</div></section>
    </div>
    <div className="os-owner-grid os-owner-lower"><section className="os-panel"><div className="os-section-title"><h2>{tr(lang,'المبالغ المنتظرة','Receivables')}</h2><button onClick={()=>go('business')}>{tr(lang,'التحصيل','Collection')}<ArrowUpRight/></button></div><div className="os-owner-list">{snapshot?.receivables.map(row=><button key={row.id} onClick={()=>go('finance')}><span className={`os-icon ${row.is_overdue?'risk':''}`}><FileCheck2/></span><div><b>REID-{String(row.number).padStart(5,'0')} · {row.counterparty}</b><small>{row.due_date?`${tr(lang,'الاستحقاق','Due')} ${row.due_date}`:tr(lang,'بدون تاريخ استحقاق','No due date')}</small></div><strong>{money(row.balance,row.currency)}</strong>{row.is_overdue&&<i>{tr(lang,'متأخر','Overdue')}</i>}</button>)}{snapshot&&!snapshot.receivables.length&&<p className="os-muted">{tr(lang,'لا توجد مبالغ معلقة.','No outstanding receivables.')}</p>}</div></section>
      <section className="os-panel"><div className="os-section-title"><h2>{tr(lang,'المشاريع المحتاجة متابعة','Projects needing attention')}</h2><button onClick={()=>go('projects')}>{tr(lang,'المشاريع','Projects')}<ArrowUpRight/></button></div><div className="os-owner-list">{snapshot?.projects.map(row=><button key={row.id} onClick={()=>{go('projects');history.replaceState({},'',`/projects/${row.id}`);dispatchEvent(new PopStateEvent('popstate'));}}><span className={`os-icon ${row.risk_count||row.overdue_tasks?'risk':''}`}><FolderKanban/></span><div><b>{row.name}</b><small>{row.target_date?`${tr(lang,'الهدف','Target')} ${row.target_date}`:tr(lang,'لا يوجد موعد مستهدف','No target date')}</small></div><strong>{row.risk_count?tr(lang,`${row.risk_count} مؤشر خطر`,`${row.risk_count} at-risk KPI`):row.overdue_tasks?tr(lang,`${row.overdue_tasks} مهمة متأخرة`,`${row.overdue_tasks} overdue tasks`):tr(lang,'على المسار','On track')}</strong></button>)}{snapshot&&!snapshot.projects.length&&<p className="os-muted">{tr(lang,'لا توجد مشاريع نشطة.','No active projects.')}</p>}</div></section>
    </div>
    <section className="os-panel os-owner-stages"><div className="os-section-title"><h2>{tr(lang,'أين يقف العمل؟','Where does business stand?')}</h2><button onClick={()=>go('business')}>{tr(lang,'دورة العمل','Business flow')}<ArrowUpRight/></button></div><div>{snapshot?.stages.filter(row=>!['cancelled'].includes(row.stage)).map(row=><article key={row.stage}><span>{lang==='ar'?(stageText[row.stage]?.ar||row.stage):(stageText[row.stage]?.en||row.stage)}</span><b>{row.count}</b><small>{money(row.value_omr)}</small></article>)}</div></section>
    {snapshot&&<p className="os-owner-asof"><Clock3/>{tr(lang,'آخر تحديث','Last updated')} {new Date(snapshot.as_of).toLocaleString(lang==='ar'?'ar-OM':'en-OM',{timeZone:'Asia/Muscat'})} · {tr(lang,'المجاميع المالية هنا بالريال العُماني فقط','Financial totals shown here are OMR only')}</p>}
  </main>;
}

function Metric({icon,label,value,note,risk=false}:{icon:React.ReactNode;label:string;value:string;note:string;risk?:boolean}){return <section className={risk?'risk':''}><span>{icon}<small>{label}</small></span><b>{value}</b><p>{note}</p></section>;}
