import { ArrowUpRight, ArrowDown, Code2, Layers3, Sparkles, MoveUpRight, Check, Workflow, Globe2 } from 'lucide-react';
import type { Page } from './routes';
import reidLogo from '../assets/img/reid-logo.svg';

export function PublicHome({lang,go}:{lang:'ar'|'en';go:(page:Page)=>void}) {
  const ar=lang==='ar';
  const contact=`https://wa.me/${import.meta.env.VITE_WHATSAPP_NUMBER||'96897308003'}`;
  return <main className="reid-home">
    <section className="reid-hero"><div className="reid-hero-copy"><span className="os-eyebrow"><i/> {ar?'تقنية عُمانية. طموح أبعد.':'OMANI ROOTS. GREATER POSSIBILITIES.'}</span><h1>{ar?<>أفكار تستحق<br/>أن تصبح <em>واقعًا.</em></>:<>Good ideas.<br/><em>Built for real.</em></>}</h1><p>{ar?'نصمّم ونبني منتجات رقمية وحلول ذكاء اصطناعي، تقرّبك من هدفك وتسهّل العمل كل يوم.':'We design and build digital products and AI solutions that move you closer to your goals, every day.'}</p><div className="reid-hero-actions"><a className="os-primary" href={contact} target="_blank" rel="noreferrer">{ar?'خلّنا نبدأ مشروعك':'Let’s build your idea'}<ArrowUpRight/></a><a href="#approach" className="os-text-link">{ar?'تعرّف على طريقتنا':'Discover our approach'}<ArrowDown/></a></div><div className="reid-hero-note"><span>REID</span><p>{ar?'نفهم بعمق. نبني بإتقان. نتطور معك.':'Understand deeply. Build thoughtfully. Grow together.'}</p></div></div>
      <div className="reid-hero-art" aria-label={ar?'الفكرة تتطور إلى منتج مع ريّد':'An idea becomes a product with Reid'}><div className="reid-art-grid"/><div className="reid-art-orbit orbit-one"/><div className="reid-art-orbit orbit-two"/><div className="reid-art-center"><img src={reidLogo} alt=""/><b>{ar?'ريّد':'Reid'}</b><small>IDEA → IMPACT</small></div><div className="reid-art-tag tag-one"><Code2/><span>{ar?'منتجات تُستخدم':'Products people use'}</span></div><div className="reid-art-tag tag-two"><Sparkles/><span>{ar?'ذكاء يخدم العمل':'Intelligence at work'}</span></div><div className="reid-art-tag tag-three"><Check/><span>{ar?'من الفكرة إلى الإطلاق':'From idea to launch'}</span></div><span className="reid-art-coordinate">23.5880° N / 58.3829° E</span></div>
    </section>
    <section className="reid-services" id="services"><div className="reid-section-heading"><span className="os-eyebrow">01 / {ar?'ما نبنيه':'WHAT WE BUILD'}</span><h2>{ar?<>تقنية لها دور.<br/>وأثر تقدر تشوفه.</>:<>Technology with purpose.<br/>Impact you can see.</>}</h2><p>{ar?'نبدأ بالمشكلة التي تستحق الحل، ونختار التقنية التي تخدمها.':'Start with a problem worth solving. Choose the technology that serves it.'}</p></div><div className="reid-service-grid">{[
      {icon:<Code2/>,n:'01',title:ar?'منتجات رقمية':'Digital products',text:ar?'مواقع وتطبيقات ومنصات تُصمّم حول احتياج المستخدم، وتبنى لتتطور.':'Websites, applications and platforms designed around people, built to evolve.'},
      {icon:<Sparkles/>,n:'02',title:ar?'ذكاء اصطناعي عملي':'Practical AI',text:ar?'مساعدون يفهمون السياق، يبحثون في المعرفة، ويساعدون الفريق ينجز.':'Assistants that understand context, search knowledge and help your team deliver.'},
      {icon:<Workflow/>,n:'03',title:ar?'أنظمة تربط العمل':'Connected operations',text:ar?'نبسّط الإجراءات ونربط الأدوات، لتصير المعلومات أقرب والقرارات أوضح.':'Simpler processes and connected tools, bringing information closer and decisions into focus.'},
    ].map(s=><article key={s.n}><div><span className="os-icon">{s.icon}</span><small>{s.n}</small></div><h3>{s.title}</h3><p>{s.text}</p><a href={contact} target="_blank" rel="noreferrer">{ar?'نتكلم عن فكرتك':'Let’s talk about your idea'}<MoveUpRight/></a></article>)}</div></section>
    <section className="reid-approach" id="approach"><div><span className="os-eyebrow">02 / {ar?'كيف نشتغل':'HOW WE WORK'}</span><h2>{ar?<>شراكة واضحة.<br/>من البداية.</>:<>A clear partnership.<br/>From day one.</>}</h2><p>{ar?'تكون قريبًا من كل خطوة، وتعرف ما يُبنى ولماذا وما الخطوة القادمة.':'Stay close to every step. Know what is being built, why it matters, and what comes next.'}</p></div><div className="reid-steps">{(ar?[['نفهم','نحدد الهدف، المستخدم، والمشكلة التي نحلها.'],['نصمّم','نحوّل الفكرة لتجربة واضحة تقدر تجرّبها.'],['نبني','ننفّذ على مراحل، ونختبر مع الاستخدام الحقيقي.'],['نطوّر','نطلق، نقيس، ونحسّن مع احتياجك.']]:[['Discover','Define the goal, the people and the problem.'],['Design','Turn the idea into an experience you can try.'],['Build','Deliver in stages and test against real use.'],['Evolve','Launch, learn and improve as your needs grow.']]).map(([title,text],i)=><article key={title}><span>0{i+1}</span><div><h3>{title}</h3><p>{text}</p></div></article>)}</div></section>
    <section className="reid-invitation"><Globe2/><span className="os-eyebrow">LET’S MAKE IT HAPPEN</span><h2>{ar?'عندك فكرة تستحق؟':'Have an idea worth building?'}</h2><p>{ar?'نحب البدايات. احكِ لنا عن مشروعك.':'We love beginnings. Tell us about yours.'}</p><a className="os-primary" href={contact} target="_blank" rel="noreferrer">{ar?'تواصل مع ريّد':'Talk to Reid'}<ArrowUpRight/></a><button className="os-text-link" onClick={()=>go('apply')}>{ar?'تحب تبني معنا؟ انضم للفريق':'Want to build with us? Join the team'}</button></section>
  </main>;
}
