import React from 'react';
import { QrCode, Smartphone, CheckCircle2, MessageCircle, Bot, ArrowUpRight, ShieldCheck, ReceiptText } from 'lucide-react';
import { localApi, localError } from './local-api';
import type { Page } from './routes';
import { supabase } from './supabase';
import { useSession } from './shell';

type Lang = 'ar'|'en';
type Status={connection:string;qr:string|null;number:string|null;lastError:string|null};
type AdminPerson={id:string;full_name:string;email:string;role:string};
type AdminLink={user_id:string;phone_e164:string;enabled:boolean;memory_enabled:boolean;style_learning_enabled:boolean;style_profile:Record<string,unknown>;sample_count:number;outbound_scope:'none'|'company'|'any';artifacts_enabled:boolean;workshops_enabled:boolean;notes_enabled:boolean;proactive_enabled:boolean};
type GroupLink={jid:string;display_name:string;enabled:boolean};
type AssistantAction={id:string;requester_id:string;kind:string;preview:string;status:string;recipient_name:string|null;recipient_phone:string|null;output_summary:string|null;error_code:string|null;created_at:string};
const choose=(lang:Lang, ar:string,en:string)=>lang==='ar'?ar:en;

export function Connections({lang,go}:{lang:Lang;go:(page:Page)=>void}) {
  const {user}=useSession();
  const [status,setStatus]=React.useState<Status|null>(null),[error,setError]=React.useState(''),[busy,setBusy]=React.useState(false);
  const [ai,setAi]=React.useState<{online:boolean;model:string}|null>(null);
  const [people,setPeople]=React.useState<AdminPerson[]>([]),[links,setLinks]=React.useState<AdminLink[]>([]),[groups,setGroups]=React.useState<GroupLink[]>([]),[actions,setActions]=React.useState<AssistantAction[]>([]),[person,setPerson]=React.useState(''),[phone,setPhone]=React.useState('');
  const loadAdmins=React.useCallback(async()=>{if(!supabase)return;const [roles,profiles,linked,groupRows]=await Promise.all([supabase.from('user_roles').select('user_id,role').neq('role','guest'),supabase.from('profiles').select('id,full_name,email'),supabase.from('whatsapp_admin_profiles').select('user_id,phone_e164,enabled,memory_enabled,style_learning_enabled,style_profile,sample_count,outbound_scope,artifacts_enabled,workshops_enabled,notes_enabled,proactive_enabled').order('created_at'),supabase.from('whatsapp_qr_groups').select('jid,display_name,enabled').order('created_at')]);if(roles.error||profiles.error||linked.error||groupRows.error){setError(choose(lang,'تعذر تحميل حسابات ومجموعات واتساب.','Could not load WhatsApp accounts and groups.'));return;}const profileMap=new Map((profiles.data||[]).map(row=>[row.id,row]));const roleRank=['owner','super_admin','admin','hr','sales','employee','project_member','research_member'];const roleMap=new Map<string,string>();for(const row of roles.data||[]){const prior=roleMap.get(row.user_id);if(!prior||roleRank.indexOf(row.role)<roleRank.indexOf(prior))roleMap.set(row.user_id,row.role);}const rows=[...roleMap].flatMap(([id,role])=>{const profile=profileMap.get(id);return profile?[{...profile,role}]:[]});setPeople(rows);setLinks((linked.data||[]) as AdminLink[]);setGroups((groupRows.data||[]) as GroupLink[]);setPerson(value=>value||rows[0]?.id||'');},[lang]);
  const load=React.useCallback(async()=>{
    try{const [nextStatus,nextActions]=await Promise.all([localApi<Status>('whatsapp/status'),localApi<AssistantAction[]>('whatsapp/actions')]);setStatus(nextStatus);setActions(nextActions);setError('');}catch(e){setError(localError(e,lang));}
  },[lang]);
  React.useEffect(()=>{void load();void loadAdmins();const timer=setInterval(()=>void load(),4000);void localApi<{online:boolean;model:string}>('ai/health').then(setAi).catch(()=>setAi({online:false,model:'gemma4:12b'}));return()=>clearInterval(timer);},[load,loadAdmins]);
  const connect=async()=>{setBusy(true);setError('');try{await localApi('whatsapp/connect',{});await load();}catch(e){setError(localError(e,lang));}finally{setBusy(false);}};
  const linkAdmin=async(e:React.FormEvent)=>{e.preventDefault();if(!supabase||!user||!person)return;const number=phone.replace(/\D/g,'');if(!/^[1-9][0-9]{7,14}$/.test(number)){setError(choose(lang,'اكتب الرقم مع مفتاح الدولة، أرقام فقط.','Enter the number with country code, digits only.'));return;}setBusy(true);const result=await supabase.from('whatsapp_admin_profiles').upsert({user_id:person,phone_e164:number,created_by:user.id,enabled:true},{onConflict:'user_id'});if(result.error)setError(choose(lang,'تعذر ربط الرقم؛ تأكد أنه غير مرتبط بحساب آخر.','Could not link the number; make sure it is not linked to another account.'));else{setPhone('');await loadAdmins();}setBusy(false);};
  const configureAdmin=async(link:AdminLink,patch:Partial<Pick<AdminLink,'enabled'|'memory_enabled'|'style_learning_enabled'|'outbound_scope'|'artifacts_enabled'|'workshops_enabled'|'notes_enabled'|'proactive_enabled'>>)=>{if(!supabase)return;setBusy(true);const result=await supabase.from('whatsapp_admin_profiles').update(patch).eq('user_id',link.user_id);if(result.error)setError(choose(lang,'تعذر تحديث الإعداد.','Could not update the setting.'));else await loadAdmins();setBusy(false);};
  const configureGroup=async(group:GroupLink,enabled:boolean)=>{if(!supabase)return;setBusy(true);const result=await supabase.from('whatsapp_qr_groups').update({enabled,updated_at:new Date().toISOString()}).eq('jid',group.jid);if(result.error)setError(choose(lang,'تعذر تحديث المجموعة.','Could not update the group.'));else await loadAdmins();setBusy(false);};
  const connected=status?.connection==='connected';
  return <main className="os-page">
    <div className="os-page-heading"><div><span className="os-eyebrow">REID / CONNECTIONS</span><h1>{choose(lang,'كل أدواتك، متصلة.','All your tools, connected.')}</h1><p>{choose(lang,'اربط رقم الشركة وتابع الخدمات التي تدعم فريقك.','Connect the company number and the services behind your team.')}</p></div></div>
    {error&&<p role="alert" className="os-alert">{error}</p>}
    <div className="os-connection-grid">
      <section className="os-panel os-qr-card"><div className="os-panel-title"><span className="os-icon"><MessageCircle/></span><div><h2>WhatsApp</h2><p>{choose(lang,'الربط بالهاتف عبر QR','Link your phone with QR')}</p></div><span className={`os-status ${connected?'good':''}`}>{connected?choose(lang,'متصل','Connected'):choose(lang,'بانتظار الربط','Awaiting connection')}</span></div>
        {connected?<div className="os-qr-success"><CheckCircle2/><h3>{choose(lang,'رقم ريّد متصل','Reid is connected')}</h3><b dir="ltr">+{status?.number}</b><button className="os-primary" onClick={()=>go('inbox')}>{choose(lang,'افتح المحادثات','Open inbox')}<ArrowUpRight/></button></div>:<div className="os-qr-setup">
          <div className="os-qr-image">{status?.qr?<img src={status.qr} width="260" height="260" alt={choose(lang,'امسح هذا الكود من واتساب لربط رقم ريّد','Scan this QR code from WhatsApp to link Reid')}/>:<><QrCode size={80}/><p>{choose(lang,'جاهز لربط هاتفك','Ready to link your phone')}</p><button className="os-primary" disabled={busy||status?.connection==='connecting'} onClick={()=>void connect()}>{busy||status?.connection==='connecting'?choose(lang,'جارٍ تجهيز الكود…','Preparing QR…'):choose(lang,'إظهار QR code','Show QR code')}</button></>}</div>
          <ol><li>{choose(lang,'افتح واتساب في هاتف رقم ريّد.','Open WhatsApp on the Reid phone.')}</li><li>{choose(lang,'الإعدادات ← الأجهزة المرتبطة ← ربط جهاز.','Settings → Linked devices → Link a device.')}</li><li>{choose(lang,'امسح الكود، ثم افتح صندوق المحادثات.','Scan the code, then open the inbox.')}</li></ol>
          <p className="os-muted">{choose(lang,'الكود يتجدد تلقائيًا. جلسة الربط محفوظة على سيرفر Reid.','The QR refreshes automatically. The linked session is stored on Reid.')}</p>
        </div>}
      </section>
      <div className="os-stack"><section className="os-panel"><div className="os-panel-title"><span className="os-icon"><Bot/></span><div><h2>{choose(lang,'مساعد ريّد','Reid assistant')}</h2><p>ai-lap</p></div><span className={`os-status ${ai?.online?'good':''}`}>{ai===null?choose(lang,'جارٍ الفحص','Checking'):ai.online?choose(lang,'جاهز','Ready'):choose(lang,'غير متاح','Unavailable')}</span></div><p>{choose(lang,'معالجة المحادثات بالذكاء المحلي. تبقى إدارة الشركة والموافقة على الإجراءات داخل حسابك.','Local intelligence for conversations. Company actions and approvals stay inside your account.')}</p><small className="os-muted">{ai?.model}</small></section>
      <section className="os-panel"><Smartphone/><h2>{choose(lang,'أنت تتحكم بالمحادثة','You control the conversation')}</h2><p>{choose(lang,'ابدأ بالرد اليدوي، وفعّل المساعد للمحادثات التي تختارها. الرد اليدوي يوقف المساعد تلقائيًا حتى تعيده أنت.','Start with human replies and enable the assistant per conversation. A manual reply pauses the assistant until you enable it again.')}</p><p className="os-muted">{choose(lang,'ربط الأجهزة غير رسمي؛ قد يحتاج إعادة مسح الكود إذا انتهت الجلسة.','Linked-device automation is unofficial and may require rescanning if the session expires.')}</p></section></div>
    </div>
    <section className="os-panel os-spaced"><div className="os-section-title"><div><h2>{choose(lang,'مساعد كل موظف عبر واتساب','WhatsApp assistant for every employee')}</h2><p>{choose(lang,'اربط الموظف برقمه وحدد ما يستطيع فعله. تبقى محادثاته وملاحظاته وذاكرته منفصلة تمامًا.','Link each employee to their number and choose what they can do. Conversations, notes and memory remain fully isolated.')}</p></div></div>
      <form className="os-quick-add" onSubmit={e=>void linkAdmin(e)}><select aria-label={choose(lang,'حساب الإداري','Administrator account')} value={person} onChange={e=>setPerson(e.target.value)}>{people.map(item=><option value={item.id} key={`${item.id}:${item.role}`}>{item.full_name||item.email} · {item.role}</option>)}</select><input dir="ltr" inputMode="tel" aria-label={choose(lang,'رقم واتساب مع مفتاح الدولة','WhatsApp number with country code')} placeholder="968XXXXXXXX" value={phone} onChange={e=>setPhone(e.target.value)} required/><button className="os-primary" disabled={busy||!person||!phone.trim()}>{choose(lang,'ربط الرقم','Link number')}</button></form>
      <div className="os-admin-links">{links.map(link=>{const linked=people.find(item=>item.id===link.user_id);const style=link.style_profile||{};return <article key={link.user_id}><div><b>{linked?.full_name||linked?.email||link.user_id}</b><small dir="ltr">+{link.phone_e164}</small><small>{linked?.role} · {choose(lang,'عينات الأسلوب','Style samples')}: {link.sample_count} · {String(style.dominant_language||'—')}</small></div><div className="os-assistant-permissions"><label><input type="checkbox" checked={link.enabled} disabled={busy} onChange={e=>void configureAdmin(link,{enabled:e.target.checked})}/>{choose(lang,'فعّال','Enabled')}</label><label><input type="checkbox" checked={link.memory_enabled} disabled={busy} onChange={e=>void configureAdmin(link,{memory_enabled:e.target.checked})}/>{choose(lang,'ذاكرة','Memory')}</label><label><input type="checkbox" checked={link.style_learning_enabled} disabled={busy} onChange={e=>void configureAdmin(link,{style_learning_enabled:e.target.checked})}/>{choose(lang,'الأسلوب','Style')}</label><label><input type="checkbox" checked={link.artifacts_enabled} disabled={busy} onChange={e=>void configureAdmin(link,{artifacts_enabled:e.target.checked})}/>{choose(lang,'ملفات وصور','Files & images')}</label><label><input type="checkbox" checked={link.workshops_enabled} disabled={busy} onChange={e=>void configureAdmin(link,{workshops_enabled:e.target.checked})}/>{choose(lang,'الورش','Workshops')}</label><label><input type="checkbox" checked={link.notes_enabled} disabled={busy} onChange={e=>void configureAdmin(link,{notes_enabled:e.target.checked})}/>{choose(lang,'الملاحظات','Notes')}</label><label><input type="checkbox" checked={link.proactive_enabled} disabled={busy} onChange={e=>void configureAdmin(link,{proactive_enabled:e.target.checked})}/>{choose(lang,'المبادرة','Initiative')}</label><label>{choose(lang,'الإرسال','Sending')}<select value={link.outbound_scope} disabled={busy} onChange={e=>void configureAdmin(link,{outbound_scope:e.target.value as AdminLink['outbound_scope']})}><option value="none">{choose(lang,'مقفّل','Off')}</option><option value="company">{choose(lang,'داخل الشركة','Company')}</option><option value="any">{choose(lang,'أي رقم','Any number')}</option></select></label></div></article>;})}</div>
      <div className="os-section-title"><div><h3>{choose(lang,'مجموعة المالك','Owner group')}</h3><p>{choose(lang,'المجموعة مثبتة برقمها الحقيقي ولا تُقبل أي مجموعة أخرى. يرد فقط على رسائل المالكين المصرح لهم.','The group is pinned by its exact ID; no other group is accepted. Only authorized Owners receive replies.')}</p></div></div>
      <div className="os-admin-links">{groups.length?groups.map(group=><article key={group.jid}><div><b>{group.display_name}</b><small dir="ltr">{group.jid}</small><small>{choose(lang,'يرد عند: ريد، Reid، منشن، أو الرد على رسالته','Replies to: Reid, a mention, or a reply to its message')}</small></div><label><input type="checkbox" checked={group.enabled} disabled={busy} onChange={e=>void configureGroup(group,e.target.checked)}/>{choose(lang,'مفعّلة','Enabled')}</label></article>):<p className="os-muted">{choose(lang,'لم تُسجل مجموعة المالك بعد.','The Owner group has not been registered yet.')}</p>}</div>
      <p className="os-muted">{choose(lang,'يحذف ريّد رموز التحقق وكلمات المرور ومفاتيح الوصول قبل إدخال النص في الذاكرة أو السياق.','Reid redacts verification codes, passwords and access keys before text enters memory or context.')}</p>
    </section>
    <section className="os-panel os-spaced"><div className="os-section-title"><div><h2><ReceiptText/> {choose(lang,'الطلبات والإيصالات','Requests & receipts')}</h2><p>{choose(lang,'سجل واضح لكل موافقة وإرسال، من طلب التنفيذ حتى النتيجة الفعلية.','A clear log from approval through the actual delivery result.')}</p></div><ShieldCheck/></div><div className="os-action-log">{actions.length?actions.slice(0,30).map(action=>{const requester=people.find(item=>item.id===action.requester_id);return <article key={action.id}><div><b>{action.preview}</b><small>{requester?.full_name||requester?.email||action.requester_id} · {new Date(action.created_at).toLocaleString(lang==='ar'?'ar-OM':'en-GB')}</small></div><span className={`os-status ${action.status==='completed'?'good':''}`}>{action.status}</span><small dir="ltr">#{action.id.slice(0,8)}</small>{action.error_code&&<small className="os-action-error">{action.error_code}</small>}</article>}):<p className="os-muted">{choose(lang,'لا توجد طلبات بعد. ستظهر أوامر واتساب المؤكدة هنا.','No requests yet. Confirmed WhatsApp actions will appear here.')}</p>}</div></section>
  </main>;
}
