begin;

create table if not exists public.reid_meeting_turns (
  id bigint generated by default as identity primary key,
  meeting_id uuid not null references public.reid_meetings(id) on delete cascade,
  owner_id uuid not null references auth.users(id) on delete cascade,
  role text not null check (role in ('user','assistant')),
  body text not null check (length(body) between 1 and 1200),
  created_at timestamptz not null default now()
);

create index if not exists reid_meeting_turns_session_idx on public.reid_meeting_turns(meeting_id,created_at desc);
alter table public.reid_meeting_turns enable row level security;
drop policy if exists reid_meeting_turns_owner_read on public.reid_meeting_turns;
create policy reid_meeting_turns_owner_read on public.reid_meeting_turns for select to authenticated
  using (owner_id=auth.uid() and public.is_admin());
revoke insert,update,delete on public.reid_meeting_turns from anon,authenticated;
grant select on public.reid_meeting_turns to authenticated;

comment on table public.reid_meeting_turns is 'Bounded live meeting dialogue used for continuity. Service-role writes; the owning administrator may inspect it.';

commit;
